feat: 스터디 시작 구현
woowacourse-teams/2023-yigongil pull request #119
Opened 2023-07-26 06:43 UTC by kevstevie

## 😋 작업한 내용

스터디 시작 구현

스터디 시작시 라운드들의 끝나는 시점 초기화
스터디의 processingStatus 변경

## 🙏 PR Point

eventListener로 시작 이벤트 발행

## 👍 관련 이슈

- Resolved : #90

2023-07-26 08:02 UTC, CFalws requested changes

2023-07-26 08:02 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/application/RoundService.java
>      // TODO: 2023/07/20 study 시작기능에서 호출해서 사용
todo 삭제해 주세요~

2023-07-26 08:02 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    public void startStudy() {
시작일자가 예상 시작일과 달랐을 때 startAt을 update 해야할 것 같아요
시작할 때 updateStartAt 같은 메서드를 호출하는 것은 어떨까요?

2023-07-26 08:02 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/application/StudyEventListener.java
> +                LocalDateTime.now(),
스터디의 시작일자와의 동기화를 위해 LocalDateTime.now() 보다는 study.getStartAt은 어떨까요?

2023-07-26 08:02 UTC, CFalws commented on backend/src/test/java/com/yigongil/backend/application/RoundServiceTest.java
> +//    @Test
주석 푸시면 좋을 거 같네요~

2023-07-26 08:03 UTC, poi1649 approved these changes
적절한 트랜잭셔널 이벤트 사용인 것 같습니다. 👍 커멘트 남기것만 확인해주세요

2023-07-26 08:03 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/RoundService.java
> +    @Transactional
👍

2023-07-26 08:03 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        study.startStudy();
p3: startStudy 안에 validateMaster가 있어도 괜찮을 것 같아요

2023-07-26 08:03 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/StudySteps.java
> +                .header(HttpHeaders.LOCATION);
p1: 이거 기준을 다같이 맞춥시다

2023-07-26 08:03 UTC, poi1649 commented on backend/src/test/resources/features/study-progress.feature
> +    Then 스터디의 남은 날짜가 null이 아니다.
👍

2023-07-26 09:30 UTC, kevstevie commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/StudySteps.java
> +                .header(HttpHeaders.LOCATION);
이거 다들 정렬 설정이 다른가 자동정렬할때마다 난리나는거 같아요

2023-07-26 12:14 UTC, yujamint approved these changes
주드 고생하셨습니다~ 간단한 코멘트 남겼으니 확인 후 반영 부탁드려요. 어프루브하겠습니다!

2023-07-26 12:14 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/RoundService.java
> +    @Transactional
p3: 이미 클래스에서 `@Transactional`을 사용하고 있는데, 메서드에서 한 번 더 사용하는 이유가 따로 있을까요??

2023-07-26 12:14 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/application/StudyServiceTest.java
> +            publisher);
p4: 괄호 앞에 개행이 들어가야 될 것 같아요~

2023-07-27 02:21 UTC, CFalws approved these changes
고생하셨습니다~

2023-07-27 02:22 UTC, merged