feat: 프로필 조회 기능 추가
woowacourse-teams/2023-yigongil pull request #125
Opened 2023-07-27 07:43 UTC by poi1649

## 😋 작업한 내용

- [x] 프로필 정보 조회 기능 추가
- [x] 내 정보 조회 기능 추가

## 🙏 PR Point

- 서비스 메서드 하나 더 만들기 싫어서 Response 재활용을 컨트롤러에서 했는데 어떤가요
- MemberService가 메서드 재활용하려고 다른 서비스 의존하는데 어떤가요

## 👍 관련 이슈

- Resolved : #78

2023-07-27 08:36 UTC, kevstevie approved these changes
테스트도 깔끔하고 좋네요 
성공 라운드 로직만 확인해주세요

2023-07-27 08:36 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/MemberService.java
> +        for (Study study : studies) {
suggestion 기능 어케쓰는지 모르겠어요
이부분 로직 
```
return (int) studies.stream()
                .map(Study::getRounds)
                .flatMap(List::stream)
                .filter(round -> round.isNecessaryToDoDone(member))
                .count();
```

훨씬 깔끔할 것 같습니다

2023-07-27 08:36 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +                .filter(roundOfMember -> roundOfMember.getMember().equals(member))
RoundOfMember에 메서드 만들어주는 편이 좋을 것 같네요

2023-07-27 08:36 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMemberRepository.java
> +    List<StudyMember> findAllByMemberIdAndParticipatingAndNotEnd(@Param("memberId") Long memberId);
jdk 버전도 똑같은거 쓰는데 왜 이런 문제가 생길까요??

2023-07-27 10:42 UTC, kevstevie approved these changes
좋습니다

2023-07-27 10:42 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/MemberService.java
> +                         StudyService studyService) {
개행이 이게 맞나요

2023-07-27 10:42 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/MemberService.java
> +        return new ProfileResponse(
서비스 레이어 두개 만드는거 나중에 이야기해보죠

2023-07-27 18:24 UTC, yujamint requested changes
고생하셨습니다 포이~ 몇가지 코멘트 남겼으니 확인 부탁드려요

2023-07-27 18:24 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/MemberService.java
> +                (double) studyService.calculateSuccessRate(member),
p3: int로 반환되는 값을 double로 캐스팅하는 것은 response의 형태를 맞춰주기 위함인 걸까요? 좀 더 값이 의미있게 쓰이려면 `calculateSuccessRate()`는 double 타입을 반환하면 어떨까 싶네요.

2023-07-27 18:24 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMember.java
> +        return !studyResult.equals(StudyResult.NONE);
p3: 저는 enum의 경우 `==` 또는 `!=`으로 비교하는 게 더 보기 좋더라고요. 어떻게 생각하시나요?

```suggestion
        return studyResult != StudyResult.NONE;
```

2023-07-27 18:24 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMember.java
> +        return studyResult.equals(StudyResult.SUCCESS);
위와 같은 내용입니다.

```suggestion
        return studyResult == StudyResult.SUCCESS;
```

2023-07-27 18:24 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/ui/MemberController.java
> +        );
p5: 제 생각엔, 어차피 DTO가 왔다갔다 하는 것이기 때문에 현재로써는 문제가 없어 보이네요.

2023-07-28 01:54 UTC, kevstevie approved these changes

2023-07-28 01:54 UTC, CFalws approved these changes

2023-07-28 01:55 UTC, yujamint approved these changes

2023-07-28 01:56 UTC, merged