feat: 스터디 진행 기능 추가
woowacourse-teams/2023-yigongil pull request #127
Opened 2023-07-27 12:46 UTC by CFalws

## 😋 작업한 내용

스터디 진행 기능 추가했습니다~ 

## 🙏 PR Point

딱히 없네용~ ㅎㅎ

## 👍 관련 이슈

- Resolved : #108

2023-07-27 12:59 UTC, kevstevie requested changes
까다로운 기능인데 잘 구현하셨네요 
리뷰 확인해주세요

2023-07-27 12:59 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        System.out.println("StudyService.proceedRound");
검거

2023-07-27 12:59 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        System.out.println("StudyService.startStudy");
검거

2023-07-27 12:59 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +        final Optional<Round> nextRound = rounds.stream()
final 지워주세요

2023-07-27 12:59 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +        if (nextRound.isPresent()) {
if 문 대신 ifPresentOrElse 메서드를 쓰면 optional을 더 유의미하게 쓸 수 있을 거 같네요

2023-07-27 12:59 UTC, kevstevie commented on backend/src/main/resources/application-local.yml
> +    driver-class-name: org.h2.Driver
왜 바뀐거죠
로컬 h2로 가나요

2023-07-27 12:59 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyRepository.java
> +    List<Study> findByProcessingStatus(ProcessingStatus processingStatus);
findAllByProcessingStatus는 어떤가요
문제는 없지만 통일성을 위해서

2023-07-27 12:59 UTC, kevstevie commented on backend/src/test/resources/application.yml
> +  round-update: 0/2 * * * * ?
테스트 환경 분리 좋네요

2023-07-27 13:31 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +        if (nextRound.isPresent()) {
추후에 study.end같은 메서드를 통해서 event 발행하는 방식으로 사용하게 수정할 수 있겠네요

2023-07-27 14:32 UTC, poi1649 requested changes
어려운 기능구현 잘 해주셨네요 @yujamint 도 고생많으셨습니다. 👍 👍 
커멘트 몇 개 남겼으니 확인해주세요~~

2023-07-27 14:32 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/RoundService.java
> +            int leftDays = (int) ChronoUnit.DAYS.between(LocalDateTime.now(), endAt) + 1;
👍

2023-07-27 14:32 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +               .filter(study -> study.isCurrentRoundEndAt(now))
p3: `오늘 끝나는 스터디를 조회한다` 라는 의미로 변수명을 now 보다는 today 정도로 바꿔줘도 좋을 것 같아요. now 라고 하니 더 세밀한 시간을 검증할 것 같아 한 번에 와닿지 않는 느낌이네요

2023-07-27 14:32 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/config/DateConfig.java
> +        return LocalDate.now();
p1: 빈으로 등록하면 서버를 실행하는 순간(컨텍스트를 실행하는 순간)으로 날짜가 고정되어서 다음날부터는 라운드업데이트가 잘 안 이루어질수도 있을 것 같은데 어떤식으로 실행될까요? 🤔

2023-07-27 14:32 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/StudyProgressStep.java
> +        Thread.sleep(Duration.ofSeconds(2).toMillis());
p2: 물론 @Given안의 문자열이 명확하지만 나중에 보면 헷갈릴수도 있으니 매직넘버에도 이름을 설정해주어도 좋을 것 같네요
```suggestion
        Thread.sleep(Duration.ofSeconds(ONE_DAY).toMillis());
```

2023-07-27 14:32 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/StudyProgressStep.java
> +        assertThat(studyDetailResponse.currentRound()).isNotEqualTo(1);
p3: 더 상세한 검증은 힘들까요?

2023-07-27 14:32 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/domain/study/StudyTest.java
> +
꼼꼼한 테스트 💯 👍 🙇

2023-07-28 01:18 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/config/DateConfig.java
> +        return LocalDate.now();
RequestScope를 사용하는건 어떨까요

2023-07-28 02:48 UTC, yujamint approved these changes

2023-07-28 02:48 UTC, poi1649 approved these changes

2023-07-28 02:48 UTC, kevstevie approved these changes

2023-07-28 02:48 UTC, merged