An/feature/120 studymanagement inflate
woowacourse-teams/2023-yigongil pull request #140
Opened 2023-07-30 13:22 UTC by RightHennessy

## 😋 작업한 내용

- ViewPager 연결
- 스터디의 선택 투두 RecyclerView 구현
- 스터디의 멤버 RecyclerView 구현
- 이전 회차, 다음 회차 버튼에 대한 로직 구현

## 🙏 PR Point

뷰페이저 어댑터의 리스트에 데이터를 넣는 과정이 회차별 정보를 각각 따로 서버 통신을 해야해서 
이에 관한 로직은 서버 연결할 때 완성될 것 같습니다 ~

## 👍 관련 이슈

- Resolved : #120

2023-07-31 02:44 UTC, inseonyun approved these changes
어떤 로직은 도메인에 있고 어떤 로직은 UI에 있고 관심사 분리가 조금 덜 된 거 같네용
피드백 남겨드린거 참고해서 반영 부탁드립니다

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementActivity.kt
> +        studyManagementViewModel.getStudyRounds(studyId, roundId)
KEY_ERROR 가 되었을 때는 어떤 플로우를 타게 되나요?

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementActivity.kt
> +            studyManagementViewModel.currentRound.value != 1
매직 넘버

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementActivity.kt
> +        }
페이지 계산 로직이 뷰에 있어야하는게 맞을까요?

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +        val currentStudy = studyRounds.value?.get(currentItemId) ?: throw IllegalStateException()
업데이트하지 못하면 터진다..? 
무시무시한 앱이군요...
의도한 흐름인가요?

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                study = studyDetails.find { it.necessaryTodo.todoId == todoId }!!
!! 
해결할 방법이 없을까요?

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                study = studyDetails.find { it.optionalTodos.any { it.todo.todoId == todoId } }!!
!!
이하 동문

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                todo = study.optionalTodos.find { it.todo.todoId == todoId }!!.todo
!!

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementMemberViewHolder.kt
> +            }
if-else 보다
그냥 return 시켜서 분기 처리 해도 될듯 합니다?

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAdapter.kt
> +            1 -> StudyManagementOptionalTodoAddViewHolder.from(parent, studyManagementClickListener)
매직 남바

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAdapter.kt
> +            1 -> (holder as StudyManagementOptionalTodoAddViewHolder).bind(getItem(position))
매직 남바 2

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAdapter.kt
> +            else -> (holder as StudyManagementOptionalTodoViewHolder).bind(getItem(position))
분기처리 else에서 뷰홀더 연결보다는 1 -> StudyManagementOptionalAdd...ViewHolder 처럼
2 -> StudyManagementOptionalViewHolder 이렇게 처리하고 else에서는 예외를 발생하는 것이 명시적이고 좋을 거 같아요

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAddViewHolder.kt
> +    }
추후에 쓰일 함수인가여?

아니라면 상위 클래스에 bind 함수를 굳이 둬서 하위 클래스에서 이러한 불필요한 함수 구현부를 계속 두게 돼서 불편할 거 같아요

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/model/StudyMemberUiModel.kt
> +    fun progressPercentage(): Int = if (isDone) 100 else 0
ui model에 있어야할 로직인가요?

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/res/layout/item_study_management.xml
> +            app:isVisible="@{role.Companion.isMaster(studyManagement.role)}"
오,,신기

2023-07-31 02:44 UTC, inseonyun commented on android/app/src/main/res/layout/item_study_management_study_member.xml
> +            type="com.created.team201.presentation.studyManagement.StudyMemberClickListener" />
그냥 갑자기 든 생각인데, xml에서 이렇게 개발자가 만든 listener라는 함수만을 받도록 만드는 것과
kotlin.jvm.functions... 을 받는 것과 어떤게 더 나을까욤
저는 이왕 추상화하는 거 후자가 더 나을 거 같단 생각이 드네요

2023-07-31 03:33 UTC, inseonyun commented
+ menu 파일에 studyManagement 메뉴 파일 언제 추가 된건지 모르겠는데 네이밍 확인 부탁드립니당 study_list라고 되어있길래

2023-07-31 08:05 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementActivity.kt
> +        studyManagementViewModel.getStudyRounds(studyId, roundId)
아직 이부분에 대한 코드가 없습니다..
서버 연결을 하면서 오류처리를 어떻게 할지 결정할 것 같습니다.

2023-07-31 08:24 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementActivity.kt
> +        }
PageIndex에서 관리하도록 분리함슴

2023-07-31 08:27 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +        val currentStudy = studyRounds.value?.get(currentItemId) ?: throw IllegalStateException()
무시무시하죠?

2023-07-31 08:28 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                study = studyDetails.find { it.necessaryTodo.todoId == todoId }!!
산군코드라 생략하겠습니다. 

궁금한점이 가짜 study를 생성해서 넣어주는게 더 좋다고 생각하나요?

2023-07-31 08:28 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                study = studyDetails.find { it.optionalTodos.any { it.todo.todoId == todoId } }!!
이하 동문

2023-07-31 08:29 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                todo = study.optionalTodos.find { it.todo.todoId == todoId }!!.todo
~~

2023-07-31 08:31 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                study = studyDetails.find { it.necessaryTodo.todoId == todoId }!!
아뇨 그냥 그 뷰 안 띄우고, 토스트로 안내 해주는 것이 전 더 좋다고 봅니다

2023-07-31 08:33 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementMemberViewHolder.kt
> +            }
코드 대충읽고 리뷰 하지 마셍.

2023-07-31 09:03 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAdapter.kt
> +            1 -> (holder as StudyManagementOptionalTodoAddViewHolder).bind(getItem(position))
OptionalTodoViewType으로 분리하였습니다.

2023-07-31 09:04 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAdapter.kt
> +            else -> (holder as StudyManagementOptionalTodoViewHolder).bind(getItem(position))
OptionalTodoViewType에서 예외처리 했습니다.

2023-07-31 09:11 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAddViewHolder.kt
> +    }
제거하였습니다

2023-07-31 09:12 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAddViewHolder.kt
> +    }
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/88828858/0d127011-05cf-47a4-86b6-6ab807b59a5e)

2023-07-31 11:02 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementMemberViewHolder.kt
> +            }
<img width="463" alt="image" src="https://github.com/woowacourse-teams/2023-yigongil/assets/84364741/c68adec0-1b0c-45d0-859a-70e1cd9a41ec">

2023-07-31 11:44 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                study = studyDetails.find { it.necessaryTodo.todoId == todoId }!!
스터디 하면서 먼말인지 알아들었습니다

2023-07-31 11:57 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/model/StudyMemberUiModel.kt
> +    fun progressPercentage(): Int = if (isDone) 100 else 0
커스텀 뷰의 경우 프로그레스 바의 기본 색이 필수투두를 완료한 색상으로 지정되어 있습니다.
또한 프로그레스가 0이라면 필수투두를 미완료한 색상으로 지정되어있습니다.
다시 말해 티어를 지정해주지 않으면 필수투두를 완료 했냐 안했냐를 표현해줄 수 있습니다.
때문에 isDone으로 투두를 완료했으면 progress가 100 미완료라면 0으로 표현해주는 겁니다.
뷰의 관심사지만 액티비티 또는 xml에 위치해 있는거도 자연스럽지 않다 생각해서 그외에 가장 어울리는 파일에 작성한 것입니다. 
액티비티에 따로 로직을 나누고 적용시킨다면 databinding expression을 사용하는 의미가 약간 퇴색되는거 같습니다.
저는 일단 그렇게 생각하는데 혹시 다른 의견이 있으신가요?

2023-07-31 11:59 UTC, RightHennessy commented on android/app/src/main/res/layout/item_study_management_study_member.xml
> +            type="com.created.team201.presentation.studyManagement.StudyMemberClickListener" />
저는 생각했을 때, 이미 onClickMember 자체는 추상화된거잖아요?
근데 그 특정 추상화 중에 어떤 것을 선택하는지 정도는 오히려 명시해주는 것이
어떤 기능을 사용하고 있는지 읽기 쉽다고 생각이 들었습니다.
특히나 xml은 코드를 왔다갔다 해야하는 번거로움이 있기 때문에 더 그렇게 느껴지네용

2023-07-31 17:20 UTC, s9hn requested changes
졸린데 남기다보니 16개나 되네요... 고생하셨습니다!! 늦어서 미안해용!

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementActivity.kt
> +        }
22

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementState.kt
> +}
```kotlin
enum class StudyManagementState(@StringRes val title: Int, @StringRes val buttonText: Int) {
 
MASTER(R.string.study_management_app_bar_title_is_study_master,
R.string.study_management_end_button_is_study_master,),
MEMBER(R.string.study_management_app_bar_title_is_study_participant,
R.string.study_management_end_button_is_study_participant,)
;
}

```

sealed Class와 오브젝트를 사용한 이유가 궁금합니다(진짜모름)

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +                    },
뭐죠 이 혼란의 코드는!?!?!?!!?!?!? ㅎ내꺼군

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementMemberViewHolder.kt
> +            }
dataBinding과 viewBinding을 혼용하신 연유가 무엇인지 여쭈어 봐도 되겠습니까를 질문해도 괜찮겠습니까?

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAdapter.kt
> +            1 -> StudyManagementOptionalTodoAddViewHolder.from(parent, studyManagementClickListener)
블랙 맘바

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAddViewHolder.kt
> +        ): StudyManagementOptionalTodoAddViewHolder {
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAddViewHolder.kt
> +        ): StudyManagementOptionalTodoAddViewHolder {
스터디매니지먼트옵셔널투두애드뷰홀더

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAddViewHolder.kt
> +            }
이건 왜 여기있나용??

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoViewHolder.kt
> +            binding.onClick = studyManagementClickListener
위에도 그렇지만 함수는 가급적 1함수 = 1책임

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementViewHolder.kt
> +        setClickAddTodo()
위에와 다르게 여기서는 init에서 클릭리스너를 초기화하네요!! 일관성을 지켜봅시다!

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/model/RoundUiModel.kt
> +data class RoundUiModel(
이건 주관적인 견해입니다만, 안드로이드에 UiModel 이라는 개념은 없습니다.
그 의미 자체로 수행하고 있는건 아마 ViewModel이 아닐까 싶습니다.
ui의 상태를 나타낸다면 ㅇㅇUiState. 그것이 아니라 단순히 ui에 표기 될 엔티티 역할을 한다면, 제 생각엔 ㅇㅇUiModel보단 presentation-작업뷰-model 패키지 내에 도메인 모델처럼 해당 모델이 의미하는 객체로 네이밍하는게 맞을것 같다고 생각합니다(근래에).

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/model/StudyMemberUiModel.kt
> +    fun progressPercentage(): Int = if (isDone) 100 else 0
뷰 로직이라고 생각된다면, uiModel에 있어도 될 것 같습니다!
근데 왜 Activity에서 뷰로직을 작성하면, dataBinding의 의미가 퇴색된다고 생각했나요?

1. 뷰 로직이다. 해당 퍼센테이지의 수치가 필수투두 완료 =10000으로 바뀐다면, 뷰모델까지 바뀌는가?
- UiModel, BindingAdapter, Activity에 위치해도 될 것 같다.
2. 해당 UiModel이 뷰에 의존하고 있는가? 뷰라고 생각하는가?
- 해당 UiModel을 혹시 뷰모델에서 생성하고 있는가? 그럼 뷰모델은 뷰를 참조하고 있는가?

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/res/layout/item_study_management.xml
> +            app:isVisible="@{role.Companion.isMaster(studyManagement.role)}"
뷰에 도메인 임포트.. 어떻게 생각하시나요?

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/res/layout/item_study_management_optional_todo_add.xml
> +            android:text="추가"
블랙맘바

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/res/layout/item_study_management_optional_todo_add.xml
> +            android:layout_height="40dp"
고정dp 최선인가요!?

2023-07-31 17:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +    fun updateCurrentPage(pageIndex: Int) {
Round라는 도메인의 책임으로 보긴 힘들까요?

2023-08-01 01:26 UTC, inseonyun commented on android/app/src/main/res/layout/item_study_management_study_member.xml
> +            type="com.created.team201.presentation.studyManagement.StudyMemberClickListener" />
흐음음음

2023-08-01 06:46 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementOptionalTodoAddViewHolder.kt
> +            }
분리 했습니다

2023-08-01 06:48 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/model/RoundUiModel.kt
> +data class RoundUiModel(
이 부분에 대해 더 고민해봐야할 것 같네요. 
지금 당장 코드에 반영하지는 못하겠지만, 추후 리팩터링에 반영해보겠습니다.

2023-08-01 06:59 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/StudyManagementViewModel.kt
> +    fun updateCurrentPage(pageIndex: Int) {
round와 page의 개념이 모두 있는데, 이 부분은 Page의 개념이어서 기존에 만들어두었던 PageIndex 도메인을 사용하도록 코드를 변경하였습니다.

2023-08-02 01:41 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/studyManagement/adapter/StudyManagementMemberViewHolder.kt
> +            }
데이터 바인딩과 뷰바인딩을 혼용하면 안되는 이유가 있을까요?
uiModel에서 context를 참조하게 해야 string을 가져올 수 있는데, 이게 uiModel에서 이뤄져도 되는일인지 잘 모르겠습니다.

2023-08-02 02:00 UTC, s9hn approved these changes
LGTM~

2023-08-02 02:02 UTC, merged