[홈 탭] 홉 탭 디자인 및 기능 구현
woowacourse-teams/2023-yigongil pull request #15
Opened 2023-07-16 08:39 UTC by s9hn

## 😋 작업한 내용

- 홈 탭 디자인 구성
- 홈 탭 카드 뷰페이저 구현
  - 뷰페이저 커스텀 구현
- 홈 탭 잔디 리사이클러뷰 구현
- 홈 탭 선택 투두 리사이클러뷰 구현

## 🙏 PR Point

### 리사이클러뷰 최적화
리사이클러뷰 최적화를 위해 적용한 방법은 아래와 같습니다.
1. RecyclerView.Adapter -> ListAdapter 전환
- 리스트 어댑터는 리사이클러뷰 어댑터가 지원하는 모든 기능을 지원합니다.
- DiffUtil 구현을 쉽게 합니다.
  - DiffUtil은 아이템 변경에 대한 notify를 명시하지 않고도 아이템의 변경 사항을 전달할 수 있습니다.
  - 아이템 변경 적용을 메인스레드가 아닌 백그라운드 스레드에서 진행합니다.

2. setHasFixedSize(true)
- 리사이클러뷰는 아이템이 변경될 때마다, 사이즈가 변경될 수 있는 View이며, 초기화마다 onMeasure, onDraw와 같은 메서드를 호출합니다.
- 해당 메서드를 true로 바꾸어주어, size가 고정임을 명시하고, 비용이 큰 메서드 호출을 막습니다.

3.  setHasStableIds(true)
- 아이템마다 포지션을 고유ID로 갖는것이 아닌, 아이템 자체의 고유ID를 이용해 아이템마다 고유ID를 부여합니다.
- 아이템마다 고유ID를 가지고 있으므로, 똑같은 아이템을 띄울경우, onBindViewHolder를 호출하지 않고, 이미 만들어진 해당 아이템을 재사용합니다.

- 리스트 어댑터를 사용하고, 고유 ID를 부여하였음에도 선택투두 아이템의 깜빡임 현상이 해결되지 않습니다. 아시는분 댓 ㅎ
- 커스텀 뷰페이저에 대한 코드는.. 긁어온거라 완벽히 이해하지는 않았습니다 이것저것 draw하는것만 이해함스..

## 👍 관련 이슈

- Resolved : #7

2023-07-18 01:02 UTC, RightHennessy reviewed
さんくん ~ 너무 수고햇졍..
특히나 잔디 UPDATE 하는 로직은 .. 매우 복잡하구만

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        binding.lifecycleOwner = this
여기서 this는 어떤 lifecycle인가요?
observe 하실 때 사용하신 viewLifeCycleOwner와 어떤 차이점이 있어 다르게 사용하셨는지 궁금합니다.

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        customViewPager.setCustomViewPager()
CustomViewPager 내부에서 init 블럭을 통해 초기화 하지 않고 setCustoViewPager를 직접 호출해주시는 이유가 있을까요?

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/HomeViewModel.kt
> +            studyUiModel.takeIf { todoUiModel -> !todoUiModel.optionalTodos.any { it.todoId == id } }
takeIf 함수.. 매우 흥미롭군요 🧐

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/adapter/viewholder/DashboardViewHolder.kt
> +    }
오.. binding을 이렇게 전달할 수도 있군요.. 하나 배워갑니다.

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/adapter/viewholder/DashboardViewHolder.kt
> +    }
apply로 코드를 묶으면 가독성이 더 높아질 수 있지 않을까여?

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/res/layout/item_home.xml
> +            android:text="선택투두"
string으로 ㅃ ㅐ줘잉

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/res/layout/item_home_grass.xml
> +            android:layout_marginBottom="2dp"
?~! 왜죠?

2023-07-18 01:02 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/adapter/DashboardAdapter.kt
> +    }
id를 처음부터 Long으로 저장하면 변환작업이 필요없지 않을까요?

2023-07-18 01:29 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/home/adapter/viewholder/DashboardViewHolder.kt
> +    }
뭐가 달라지나요? 저도 원래 with(binding) 으로 다 묶었는데,,
뎁스 하나 더 깊어지고, 별 다른게 없어서,, apply써도 3줄아닌가요 ..

2023-07-18 01:31 UTC, s9hn commented on android/app/src/main/res/layout/item_home_grass.xml
> +            android:layout_marginBottom="2dp"
피그마 디자이너가 간격을 저렇게 줬습니다.

2023-07-18 04:19 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        binding.lifecycleOwner = this
this는 fragment의 lifecycle입니다. 
어떤 라이프사이클을 참조하더라도, onDestroyView에서 바인딩 참조를 해제하고 있으므로, 메모리 누수 등이 일어날 일은 없습니다.

binding.lifecycleOwner 는 바인딩 된 뷰모델이 어떤 생명주기를 따를 것인지 명시해주는 역할입니다.
해당 코드가 있어야만, 바인딩된 xml이 바인딩된 뷰모델의 라이브데이터를 따라 실시간으로 ui를 갱신할 수 있습니다.

```kotlin
  homeViewModel.observe(lifecycleOwner) {   }
```
해당 코드 2줄은 위 코드와 유사합니다.
fragment에서는 fragment의 자체 라이프사이클을 따르는 것은 위험하므로, viewLifeCycleOwner를 할당해주었습니다.

2023-07-18 04:20 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        customViewPager.setCustomViewPager()
뷰페이저의 세팅을 단순히 객체를 생성할 때 호출되는 트리거가 아닌, 외부에서 해당 객체의 함수를 트리거로써 호출하는게 옳다고 생각했습니다.

2023-07-18 04:21 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        customViewPager.setCustomViewPager()
가독성 측면에서 해당 코드로 세팅해주었슴다

2023-07-18 06:14 UTC, no1msh requested changes
さんくん!!
야하리 코딩실력이 스바라시데스가, 에..몇가지 코멘토를 남겼으까라, 확인 부탁드린다데스

2023-07-18 06:14 UTC, no1msh commented on android/app/src/main/res/layout/item_home.xml
> +            app:layout_constraintTop_toBottomOf="@+id/rv_home_grass"
이미 `id`가 존재하는 뷰를 참조하는 것이니 `+`를 떼어 주시는게 좋을 듯하네요

2023-07-18 06:14 UTC, no1msh commented on android/app/src/main/java/com/created/team201/presentation/home/adapter/viewholder/DashboardViewHolder.kt
> +    }
저도 이건 취향차이라고 보는데 개인적으론 뎁스 들어가는게 싫어서 저도 안씁니다.

2023-07-18 06:14 UTC, no1msh commented on android/app/src/main/java/com/created/team201/presentation/home/CustomViewPager.kt
> +    }
inner class로 구현하신 이유가 궁금합니다!

2023-07-18 06:14 UTC, no1msh commented on android/app/src/main/java/com/created/team201/presentation/home/adapter/viewholder/DashboardViewHolder.kt
> +    }
산군에 대한 리뷰는 아니지만 ㅎㅎ 메시지를 보내는 구조로 만들기위해 저렇게 구성하는거로 알고있습니다.

2023-07-18 14:58 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        customViewPager.setCustomViewPager()
납득했습니다.

2023-07-18 15:00 UTC, RightHennessy approved these changes
리뷰 반영 확인 굿뜨 👍

2023-07-19 05:33 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/home/CustomViewPager.kt
> +    }
본 클래스에서만 사용될 유틸이기에 캡슐화를 위해 이너클래스로 두었습니다

2023-07-19 05:52 UTC, no1msh approved these changes

2023-07-19 09:14 UTC, merged