refactor: 도메인의 default 값을 설정한다
woowacourse-teams/2023-yigongil pull request #186
Opened 2023-08-03 09:04 UTC by kevstevie

## 😋 작업한 내용

 도메인의 default 값을 설정한다

## 🙏 PR Point

3항 연산자 좀 힙한가요

## 👍 관련 이슈

- Resolved : #169

2023-08-04 16:07 UTC, yujamint requested changes
고생하셨습니다 주드~ 리뷰 확인 부탁드려요

2023-08-04 16:07 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/member/Member.java
> +        this.tier = tier != null ? tier : 1;
p4: 사소한 제안인데, 조건문을 긍정형으로 넣으면 어떨까요??
저는 처음 봤을 때 'tier가 null이 아닌 게 아니면 1을 넣어준다' 라는 의미로 해석이 되더라고요.
'tier가 null이면 1을 넣어준다'라는 게 더 직관적으로 보일 것 같아요.

```suggestion
        this.tier = tier == null ? 1 : tier;
```

2023-08-04 16:07 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +        this.roundNumber = roundNumber != null ? roundNumber : 1;
p4: 이것도 `Member.tier` 초기값 넣어줄 때랑 비슷하면 어떨까 싶어요~

2023-08-05 04:56 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/member/Member.java
> +        this.tier = tier != null ? tier : 1;
좋네요 수정했습니다

2023-08-05 05:03 UTC, yujamint approved these changes
리뷰 반영 감사합니다~ 고생하셨어요 주드

2023-08-07 06:15 UTC, CFalws approved these changes
주드 화이팅입니다 ! 주말간 고생 많으셨어요~

2023-08-07 06:24 UTC, merged