test: DatabaseCleaner 구현
woowacourse-teams/2023-yigongil pull request #209
Opened 2023-08-05 10:59 UTC by kevstevie

## 😋 작업한 내용

@DirtiesContext를 걷어내고 DatabaseCleaner 추가

## 🙏 PR Point

### 테스트 성능 비교
각각 entrypoint를 인텔리제이에서 돌렸을 때, 터미널에서 ./gradlew clean test를 돌렸을 때

### 기존 테스트 성능

![image](https://github.com/woowacourse-teams/2023-yigongil/assets/109793396/0036daeb-e82e-4d8f-91e5-cf4688ca47b5)
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/109793396/0d31f894-2db5-4995-b661-867cf23d2316)

### 변경 후 테스트 성능

![image](https://github.com/woowacourse-teams/2023-yigongil/assets/109793396/a0c2249d-8c7a-4008-9001-10609fdf9ff7)
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/109793396/f93300f8-9920-4772-b871-468bf8eb92ca)

## 👍 관련 이슈

- Resolved : #208

2023-08-05 11:34 UTC, yujamint requested changes
주드 고생하셨습니다~ 리뷰 확인 부탁드려요

2023-08-05 11:34 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +        System.out.println("tables = " + tables);
p4: 이 출력문은 특별한 의미가 있어서 남아 있는 건가요??

2023-08-05 11:34 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +    }
p3: 문자가 대문자일 경우, `_`를 추가한 뒤 소문자로 바꿔서 추가해야 할 것 같은데 현재는 언더바만 추가되는 것 같아요.
문제 없는 거 맞나요?!

2023-08-05 11:45 UTC, kevstevie commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +        System.out.println("tables = " + tables);
앗

2023-08-05 11:46 UTC, kevstevie commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +    }
toLowerCase가 붙어서 정상작동 합니다

2023-08-05 11:54 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +    }
아 그러네용 놓쳤네요 굿굿~

2023-08-07 05:51 UTC, yujamint approved these changes

2023-08-07 06:02 UTC, CFalws approved these changes
코드 잘 읽고 갑니다! 고생하셨어요~

2023-08-07 06:03 UTC, merged