feat: 유저 신고 기능 구현
woowacourse-teams/2023-yigongil pull request #280
Opened 2023-08-09 13:05 UTC by yujamint

## 😋 작업한 내용
유저 신고 기능 구현

## 🙏 PR Point

1. 로직 자체는 간단한듯 합니다. 혹시나 놓친 비즈니스 로직이 있다면 알려주세요~
2. Report 엔티티가 추가되면서 flyway를 통해서 관리되도록 sql 문을 추가했습니다. 
`ddl-auto: none`, `flyway.enabled: true`로 설정하고 로컬 환경에서 실행했을 때, 테이블이 정상적으로 생성되는 것을 확인했습니다. 확인한 이미지 첨부합니다.
<img width="921" alt="image" src="https://github.com/woowacourse-teams/2023-yigongil/assets/71512749/f0553ccc-c86f-4a1c-bc2e-11a2639e1e54">
그래도 처음 변경사항을 적용해봐서 약간 무섭네요. 유심히 봐주시면 감사하겠습니다.

## 👍 관련 이슈

- Resolved : #265

2023-08-09 14:46 UTC, kevstevie requested changes
수고하셨습니다.
제 의견으론 report라는 행위가 member에 종속되기보단 도메인의 서비스와 컨트롤러를 새로 만드는게 좋아보이는데 어떻게 생각하시나요?

2023-08-09 14:46 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +    private Member reported;
report 엔티티에 member 엔티티의 정보가 필요할까요? 식별자만 있으면 되지 않을까요

2023-08-09 14:46 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/ui/MemberController.java
> +    @PostMapping("/{reportedMemberId}/reports")
report가 member의 하위 계층이라는게 조금 어색해요

2023-08-10 01:52 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +    private Member reported;
당장은 신고 내역을 사용자가 보지 않을 정보니까 당장은 엔티티를 가질 필요는 없어 보이긴 하네요.
현재 구조에선 식별자만 가져도 전혀 문제가 없어 보이긴 하지만.. 나중에 '사용자는 본인의 신고 내역을 확인할 수 있다' 라던가, '신고 내역을 개발자가 아닌 누군가가 관리한다'와 같은 상황을 고려하면 엔티티를 가지는 것도 괜찮을 거 같아요.

Report 엔티티를 삽입하는 시점에 Member를 찾는 쿼리가 2번 더 나가긴 하겠지만, 신고 기능 자체가 애플리케이션 내에서 큰 비중을 차지하지 않을 거 같아서 성능 변화도 미미할 것 같고요.

결론은 성능 변화는 미미할 것 같으니, 확장성을 위해 남겨두면 어떨까 싶습니다!

2023-08-10 01:53 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/ui/MemberController.java
> +    @PostMapping("/{reportedMemberId}/reports")
동의합니다. 이거는 의견 주신대로 분리해보겠습니다~

2023-08-10 02:12 UTC, poi1649 approved these changes

2023-08-10 02:12 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/MemberService.java
> +                                                    .problemOccurDate(request.problemOccurDate())
p3: problemOccuredAt 정도로 바꿔도 좋아보이네용

2023-08-10 02:12 UTC, poi1649 commented on backend/src/test/resources/features/report-member.feature
> +    Given 신고 제목-"노이만 신고", 내용-"코딩 너무 잘함", 문제발생일-"3"일 전으로 신고 정보를 작성한다.
노이만 이녀석은 그냥 잘함

2023-08-10 02:15 UTC, CFalws requested changes

2023-08-10 02:15 UTC, CFalws commented on backend/src/main/resources/db/migration/V2__add_report_table.sql
> +         references member(id);
한 줄 띄워주세요~

2023-08-10 02:15 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +        validateReporterSameWithReported(reporter, reported);
회원 탈퇴 기능이 구현되면 피신고자가 탈퇴한 멤버인지 검증하는 것은 어떨까요?

2023-08-10 02:15 UTC, CFalws commented on backend/src/test/java/com/yigongil/backend/domain/report/ReportTest.java
> +}
한 줄 띄워주세요~

2023-08-10 02:55 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +        validateReporterSameWithReported(reporter, reported);
에밀이 말씀하신대로 검증이 필요하겠네요! 
근데 회원 탈퇴 기능이 생기면, 회원 관련 로직이 실행될 때마다 탈퇴한 회원은 아닌지 검증이 필요할 거 같은데, 이러한 검증은 최대한 앞 단에서 공통으로 처리하는 게 좋지 않을까요?? 가령 탈퇴하지 않은 회원만 조회한다던지... 어떤 방법이 좋을지는 모르겠네요. 어떻게 생각하시나요??

2023-08-10 03:04 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +        validateReporterSameWithReported(reporter, reported);
Authorization으로 생성된 멤버의 경우 MemberArgumentResolver에서 탈퇴 여부를 확인하는 것으로 알고 있습니다 
헌데 회원 id를 request body로 받는 등의 로직에서는 회원이 탈퇴한 회원인지 확인하는 것이 필요하겠네요
음.. 최대한 한 곳에서 공통으로 처리하는 것이 좋을 것 같기는 한데.. 
제 생각에는 MemberService에서 멤버와 관련된 세부 사항을 감추는 것이 방법이 될 수 있을 것 같아요
그래서 ReportService에서 MemberService.getActiveMember(id)를 통해 member를 찾아오면 탈퇴 관련 로직은 최대한 캡슐화 할 수 있을 거 같아요

2023-08-10 03:08 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/MemberService.java
> +                                                    .problemOccurDate(request.problemOccurDate())
좋네요.수정했습니다~

2023-08-10 03:12 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +        validateReporterSameWithReported(reporter, reported);
좋은 생각이네요. 저도 `MemberService`에서 활동 중인 회원만 조회하고, 이를 다른 서비스에서 재사용한다면 구현도 숨기고, 응집성도 높아질 것 같습니다.
일단 현재 코드도 `ReportService`에서 `MemberService.findMemberById()`를 통해 조회하고 있는데요, 만약 회원 탈퇴 기능이 들어온다면 말씀하신 방향으로 수정하도록 할게요. 👍

2023-08-10 03:15 UTC, CFalws approved these changes

2023-08-10 03:17 UTC, yujamint commented
변경사항입니다.
1. flyway 파일 prefix `V3`로 수정
2. Report 엔티티의 `problemOccurDate` 컬럼명 수정 -> `problemOccuredAt`
3. 기존에 Member 도메인의에 속해 있던 Report 도메인 컨트롤러/서비스 분리

2023-08-10 06:04 UTC, kevstevie requested changes
수정사항 리뷰 남겼습니다 확인해주세요

2023-08-10 06:04 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/ui/ReportController.java
> +    @PostMapping("/{reportedMemberId}")
신고당한 멤버의 id가 신고 컬렉션의 자원은 아닌 것 같아요
request로 옮기는게 좋을 것 같아요

2023-08-10 06:45 UTC, kevstevie approved these changes

2023-08-10 06:56 UTC, merged