feat: 스터디 신고 기능 구현
woowacourse-teams/2023-yigongil pull request #350
Opened 2023-08-12 15:52 UTC by yujamint

## 😋 작업한 내용

회원 뿐만 아니라 스터디도 신고할 수 있는 기능을 구현했습니다.

## 🙏 PR Point

### 스터디 신고 / 멤버 신고 API 분리
두 API를 각각의 엔드포인트로 분리했습니다. 그에 따라 엔티티도 분리하였습니다.

### 엔티티 분리 및 상속 관계 매핑에서 발생한 문제
1. `MemberReport`와 `StudyReport`가 `Report`를 상속 받도록 설계했습니다. 그리고 상속 관계 매핑 전략을 `SINGLE_TABLE`로 가져가며, 실제로 테이블이 Report 하나만 생성되는 것을 확인했습니다.
2. 테이블은 하나만 생성되지만, `EntityManager`를 통해 관되되는 엔티티는 `StudyReport`, `MemberReport`, `Report`3가지 모두입니다.
그래서 `DatabaseCleaner`에서 `EntityManager`를 통해 모든 엔티티를 가져오고, `truncate table`을 하는 과정에서 3가지 테이블을 모두 truncate 하려고 합니다. 이때 실제로 생성된 테이블은 Report 하나 뿐이라서 에러가 발생합니다.

즉, 상속관계 매핑에서의 싱글 테이블 전략으로 인해 `엔티티 != 테이블`로 이어지며 발생하는 문제인 것 같습니다.
일단 이 문제를 당장 해결할 수 있는 방법으로 해결을 했는데... 무조건 리팩토링 해야 하는 부분인 것 같습니다 ㅋㅋ..
혹시나 좋은 의견 있으면 남겨주시기 바라겠습니다!

## 👍 관련 이슈

- Resolved : #308

2023-08-12 16:09 UTC, kevstevie requested changes
주말인데 열심히 하시는군요
리뷰 남겼습니다!

2023-08-12 16:09 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/ReportService.java
> +    private final StudyService studyService;
단순 find만 하고 있는데 서비스가 서비스를 둘이나 의존해야 하나요?

2023-08-12 16:09 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +    Long id;
protected로 달아주세요..

2023-08-12 16:09 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/report/StudyReport.java
> +        this.reportedStudy = reportedStudy;
하위 객체가 상속하는 객체의 모든 정보를 알게 되는데 관리 지점이 두개가 되겠네요

2023-08-12 16:09 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/ui/ReportController.java
> +    @PostMapping("/members")
study와 member가 report의 하위계층인지 고민을 좀 해볼만한 지점인 것 같네요

2023-08-12 16:09 UTC, kevstevie commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +            }
이부분 해결책이 있을텐데 내일 일어나서 찾아볼게요

2023-08-13 04:27 UTC, kevstevie commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +            }
tables 생성할 때 리플렉션 통해서 해결할 수 있네요
```java
 stream().filter(entityType -> entityType.getJavaType().getSuperclass().getSimpleName().equals("BaseEntity"))
```
형태로 추가해주세요

2023-08-13 04:28 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/report/StudyReport.java
> +public class StudyReport extends Report {
기본 생성자가 없는데 protected로 만들어주세요

2023-08-13 06:57 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/ReportService.java
> +    private final StudyService studyService;
단순 조회긴 하지만, Repository를 통해 엔티티를 조회하고 결과가 없으면 비즈니스 예외를 터트리고 있는 것은 서비스이기 때문에 서비스를 의존하는 것이 더 응집성 있는 구조라고 생각했습니다.
추가로, 서비스 계층에서의 layer를 나눴을 때 현재 구조에서 신고 서비스는 회원,스터디 서비스보다 상위 layer에 존재한다고 생각합니다. 그래서 하위 layer인 두 서비스를 의존하는 것 역시 괜찮아 보입니다.

2023-08-13 07:00 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
> +    Long id;
`MemberReport`와 `StudyReport`를 같은 패키지에서 관리하니까 default 접근제어자가 더 좋겠다고 생각했는데, protected로 했을 때의 이점이 무엇일까요??

2023-08-13 07:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/ui/ReportController.java
> +    @PostMapping("/members")
음 .. 맞네요 테이블은 존재하지 않지만, 도메인 상으로는 StudyReport와 MemberReport라는 자원이 존재하는 것이니까 각각에 해당하는 url에 매핑하도록 수정하겠습니다.

2023-08-13 07:14 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +            }
잘 동작하네요 ~ 감사합니다

2023-08-13 07:18 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/report/StudyReport.java
> +        this.reportedStudy = reportedStudy;
관리 지점이 두개가 된다는 말이 어떤 의미인지 잘 모르겠네요.. 혹시 어떤 의도로 남긴 리뷰인지 알려주실 수 있나요??

2023-08-13 08:37 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/report/StudyReport.java
> +        this.reportedStudy = reportedStudy;
부모객체가 수정되면 자식객체도 수정해야한다는 의미입니다

2023-08-13 09:58 UTC, poi1649 approved these changes
스터디/멤버 신고가 사실을 다른 규칙을 적용하게 될 것 같아 아얘 상속/조합을 사용하지 않는 것이 좋을 것 같다는 느낌은 들지만, 당장은 신고에 대한 비즈니스 규칙이 없어 어떤 문제가 일어날지는 잘 상상되지 않네요.

이 부분은 코드를 미리 고민하는 것 보다 비즈니스 규칙을 정할 때 이 구조에서 일어날 문제를 고려해보면 될 것 같아 일단 approve 하겠습니다 👍 

컨벤션 관련한 리뷰만 몇 개 남겼으니 확인해주세요~

2023-08-13 09:58 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/ReportService.java
> +    }
p4: 사소하지만 이 부분 정렬이 이상하게 보이네요

2023-08-13 09:58 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/ReportService.java
> +@Transactional
p2: 저희 서비스의 각 메서드에 Transactional을 붙이는 것이 컨벤션이었던 것 같아요. 클래스에서는 제거해주면 좋겠네요 👍

2023-08-13 10:24 UTC, CFalws requested changes
고생하셨습니다!

2023-08-13 10:24 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +    public Study findStudyById(Long studyId) {
135번 라인에 존재하는
```java
public StudyDetailResponse findStudyDetailByStudyId(Member member, Long studyId) {
   Study study = studyRepository.findById(studyId)
      .orElseThrow(() -> new StudyNotFoundException("해당 스터디가 존재하지 않습니다", studyId));

```
이 부분 중복 제거 가능하겠어요~

2023-08-13 10:24 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/application/ReportService.java
> +        reportRepository.save(MemberReport.builder()
컨벤션 상 . 위치 align 부탁드릴게요~

2023-08-13 10:24 UTC, CFalws commented on backend/src/main/resources/db/migration/V6__modify_report_table.sql
> +   references study (id);
EOL 이요~

2023-08-13 10:24 UTC, CFalws commented on backend/src/main/resources/application.yml
> +  webhook-url: http://ignore
EOL이요~

2023-08-13 10:24 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/ui/ReportController.java
> +    @PostMapping("/members")
한 가지 첨언을 하자면 
/reports/members, /reports/byMember, /member-reports 등이 있을 수 있죠.
개인적으로 두번째가 나아 보입니다. 
물론 명사형이 아니라 좀 걸리고 필터 같은 역할을 한다고 느껴지지만 첫번째 것은 members가 reports의 하위 자원 같은 인상을 주고 member-reports는 세부적인 자원이 가장 상위 자원이 된다는 것에서 단점이 느껴져서요

2023-08-13 10:24 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/report/StudyReport.java
> +        this.reportedStudy = reportedStudy;
혹시 엔티티 상속을 하는 경우 부모 필드를 private으로는 할 수 없나요? 
private으로 변경했을 때 테스트가 잘 통과하는 것 같아서요
private으로 하면 주드가 염려하는 부분도 덜어질 것 같네요

2023-08-13 10:34 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
>  public class Report extends BaseEntity {
혹시 이거 abstract 클래스로 변경 가능한가요? 만약 변경하면 엔티티가 생성이 안되나요?

2023-08-13 10:40 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/ReportService.java
> +    private final StudyService studyService;
그럼 이대로 가시죠
추후에 에밀이 제안한 파사드 패턴 논의할 때 필요한 이야기 같네요

2023-08-13 10:42 UTC, kevstevie approved these changes

2023-08-13 16:08 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/report/StudyReport.java
> +        this.reportedStudy = reportedStudy;
그러네요 private 접근제어자로 수정하겠습니다.
근데 부모 객체가 수정됐을 떄 자식 객체도 수정해야 한다는 점은 그대로이지 않나 싶은데, 어떤 부분에서 주드가 염려하는 부분도 덜어진다고 생각하신 건지 알려주실 수 있나요??

2023-08-13 16:26 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/ui/ReportController.java
> +    @PostMapping("/members")
이건 정말 어렵네요 ㅋㅋ.. 일단 두 번째 방식을 채택해보겠습니다.

2023-08-13 16:35 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/report/Report.java
>  public class Report extends BaseEntity {
안 되는 줄 알고 수정했는데, 다시 확인해보니 abstract class여도 정상적으로 작동하네요! 수정했습니다~

2023-08-14 04:11 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/report/StudyReport.java
> +        this.reportedStudy = reportedStudy;
default로 필드가 열려있다면 아시다시피 같은 패키지에서(여기서는 자식 클래스들) 모두 접근할 수 있습니다. 
그러므로 차후에 자식 클래스에서 부모의 필드를 사용하게 되면,
부모 클래스의 변경이 같은 패키지 전체로 파급효과를 일으키게 됩니다.
결론은 private으로 설정하면 부모 클래스의 변경의 파급효과를 최소한으로 막을 수 있다는 얘기였습니다!

2023-08-14 04:13 UTC, CFalws approved these changes

2023-08-14 04:23 UTC, merged