feat: 리프레시 토큰 적용
woowacourse-teams/2023-yigongil pull request #357
Opened 2023-08-14 14:19 UTC by CFalws

## 😋 작업한 내용

리프레시 토큰 적용

## 🙏 PR Point

- refresh token(이하 RT)을 사용한 요청이 body로 갑니다. https라 상관이 없는건지 잘 모르겠네요. 그 javascript 코드로 공격하는 그거 괜찮나요? 

- 플로우
사전 지식
   - 리프레시를 하면 매번 새로운 AT와 RT를 발행합니다. 
   - 유저로부터 받은 RT, 현재 서버에 저장되어 있는 RT(최신 RT)가 다르다면 탈취로 간주합니다. 
   - 탈취가 발생하면 기존의 RT도 무효화합니다.
![image](https://github.com/woowacourse-teams/2023-yigongil/assets/91701137/847ed450-3064-4384-a5ad-34636a453f50)

1. 공격자가 탈취를 해서 먼저 AT, RT를 취했다고 가정합시다. 그럼 서버의 RT는 최신화 됩니다.
2. 유저가 과거의 RT로 refresh 요청을 합니다. 
3. 서버는 RT가 다르다는 것을 깨닫고 공격으로 간주합니다. 
4. 서버는 해당 유저와 관련된 모든 RT를 제거합니다. 
5. AT의 생명 주기가 충분히 짧다면 공격자는 짧은 시간동안만 AT를 사용가능합니다. 

허점: 만약 유저가 리프레시 요청을 오랫동안 하지 않는다면 공격자가 오래 쓰는 것이 가능합니다. 

## 👍 관련 이슈

- Resolved : #352

2023-08-15 06:55 UTC, kevstevie requested changes

2023-08-15 06:55 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/config/auth/JwtTokenProvider.java
> +        Long memberId = parseToken(tokenWithScheme);
토큰이 만료된 상태라면 이 부분에서 예외가 터지기 때문에 정상작동하지 않을 것 같아요

2023-08-15 06:55 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/config/auth/JwtTokenProvider.java
> +
refresh token은 만료가 없나요?

2023-08-15 06:55 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/request/TokenRequest.java
> +        String refreshToken
리프레시 토큰도 헤더로 요청을 받는게 기본 스펙인걸로 알고 잇습니다

2023-08-15 15:03 UTC, poi1649 requested changes
고생하셨습니다. 이 구조면 토큰도 꽤 안전할 것 같네요 
몇 가지 커멘트 남겼으니 확인해주세요~

2023-08-15 15:03 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/config/auth/TokenTheftDetector.java
> +        if (Objects.equals(upToDateToken, inputToken)) {
p3: null 방어 good이긴하지만, 리프레시 토큰이 memberId로 get을 했을 때 없다는 것도 탈취라고 할 수 있을까요? null검사를 먼저 실행해주고 적절한 예외를 던져주는 것도 좋아 보입니다!

2023-08-15 15:03 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/ui/LoginController.java
> +        TokenResponse tokenResponse = authService.refresh(request);
p3: 위의 메서드는 변수명이 response인데 여기는 tokenResponse네요 통일해주면 좋을 것 같아요

2023-08-15 15:03 UTC, poi1649 commented on backend/src/test/resources/features/refresh-token.feature
> +    Then "yujamint"가 인증에 실패한다.
p5: 👍

2023-08-15 23:26 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/request/TokenRequest.java
> +        String refreshToken
저도 같은 방식으로 헤더로 받되, payload에 `token_type`과 같은 claim을 추가함으로써 리프레시 토큰과 액세스 토큰을 구분한다는 거를 본 기억이 있네요

2023-08-15 23:48 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/config/auth/JwtTokenProvider.java
> +
token 만료를 두는 이유는 탈취되었을 때 해당 토큰의 오남용을 막기 위해서라고 생각이 드는데요
해당 로직에서 리프레시 토큰은 오직 1회만 사용가능한 토큰입니다

다음처럼 상황을 가정해볼게요
- 1분마다 AT 만료
- 3주마다 RT 만료

1. 공격자가 탈취를 했고 유저는 하필 그때 앱을 껐습니다. 그리고 3주동안 앱을 사용하지 않다가 3주만에 유저가 재접속을 했습니다. (이 모든 게 정말 희박한 경우지만) 이때 유저가 AT가 만료되어서 RT로 재발급 요청을 보냅니다. 이때 문제가 발생하는데 유효기한이 만료돼서 parse 할 때 에러가 발생하는 겁니다. 그렇게 되면 memberId를 우리는 알아낼 수 없습니다(base64 decode를 로우 레벨로 하지 않는 이상) 그러면 탈취 감지를 할 수 없고 예상치 못한 동작을 하게 됩니다. 

그래서 expiration을 설정하지 않았고 그게 일반적인 경우로 보입니다. 그리고 지금 같은 경우에는 RT를 단 1회만 사용할 수 있기 때문에 expiration이 대부분의 경우에 의미가 없기도 합니다.

2023-08-15 23:49 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/config/auth/JwtTokenProvider.java
> +        Long memberId = parseToken(tokenWithScheme);
아래에서 말씀드린대로 리프레시 토큰은 expiration을 설정하지 않았습니다~

2023-08-16 00:17 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/config/auth/TokenTheftDetector.java
> +        if (Objects.equals(upToDateToken, inputToken)) {
좋네요~

2023-08-16 00:26 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/config/auth/JwtTokenProvider.java
> +
혹시 만료기간을 설정하지 않으면 기본으로 설정되는 만료기간이 존재하진 않나요??
찾아봤는데 잘 안 보이네요

2023-08-16 00:34 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/request/TokenRequest.java
> +        String refreshToken
OAuth 2.0 등장할 때 발표한 [문서](https://www.rfc-editor.org/rfc/rfc6749#section-6)에서는 form 데이터를 보내긴 하네요. 
보니까 여러가지 옵션이 있는 것 같은데 한 번 조사하고 장단점 정리해서 말씀드리겠습니다~

2023-08-16 01:27 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/config/auth/JwtTokenProvider.java
> +        Long memberId = parseToken(tokenWithScheme);
그러네여 파라미터로 받는게 refresh token이네요

2023-08-16 01:47 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/config/auth/JwtTokenProvider.java
> +
만료 기간을 설정하지 않으면 만료기간이 존재하지 않습니다~ 그래서 parse error가 발생하지 않습니다

2023-08-16 05:25 UTC, kevstevie approved these changes
현재 로직이면 잘 작동할 것 같네요
수고하셨습니다.

2023-08-16 05:41 UTC, yujamint approved these changes
고생하셨습니다 에밀~

2023-08-16 08:30 UTC, poi1649 approved these changes

2023-08-16 08:31 UTC, merged