feat: 회차 멤버들의 투두 진행률 조회 api
woowacourse-teams/2023-yigongil pull request #383
Opened 2023-08-22 06:55 UTC by kevstevie

## 😋 작업한 내용

방학에 죄송합니다..

api : GET "/v1/studies/id/rounds/id/progress-rate

## 🙏 PR Point

기존 로직 domain으로 넘기고 그냥 조회 api 만들었습니다
config 클래스 중복코드가 계속 생겨서 겸사겸사 분리도 했습니다.

## 👍 관련 이슈

- Resolved : #382

2023-08-22 10:14 UTC, poi1649 approved these changes
방학에도 열일하시네요. 이번 수정보고 느낀건 Api 하나당 Service 메서드 하나가 추가로 생기는 게 생각보다 서비스의 복잡도를 높이긴 하는 것 같아요 🤔  이 부분은 더 고민해보겠습니다. 고생하셨습니다 👍

2023-08-22 10:14 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/fixture/RoundFixture.java
> +
p3: 공백 지워주세요 👍

2023-08-22 10:14 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/config/AuthConfig.java
> +                .excludePathPatterns("/v1/fake/proceed")
p3: 이 녀석을 분리해 볼 수는 없을까요?

2023-08-22 10:14 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/config/ActuatorConfig.java
> +public class ActuatorConfig {
p4: 역할에 맞게 분리된거 좋네요 👍

2023-08-22 10:53 UTC, CFalws requested changes
방학 때도 열일하시네요~ 고생하셨습니다.

2023-08-22 10:53 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +    public int calculateProgress() {
이제 RoundOfMembers 일급 객체는 필요없어서  삭제해도 되지 않나요?

2023-08-22 10:53 UTC, CFalws commented on backend/src/test/resources/features/find-round.feature
> +    When "jinwoo"가 찾은 회차의 필수 투두를 수정 내용 "<수정 투두 필수 여부>", "<수정 투두 내용>"으로 수정한다.
수정 투두 필수 여부 -> 필수 투두 완료 여부
이름이 잘못된 거 같아요~

2023-08-23 03:26 UTC, yujamint approved these changes
저도 RoundOfMembers가 이제 프로덕션 코드에서는 쓰이지 않는 것 같아서 없애면 좋을 거 같아요~ 방학에 고생하셨습니다 주드 어프루브 해놓을게용

2023-08-28 15:59 UTC, CFalws approved these changes

2023-08-30 09:26 UTC, merged