test: sharedcontext 기능 추가
woowacourse-teams/2023-yigongil pull request #387
Opened 2023-08-30 12:32 UTC by kevstevie

## 😋 작업한 내용

sharedContext에 token 을 저장하는 map 추가

step들의 모든 중복코드를 sharedContext에 넣어서 중복 제거

## 🙏 PR Point

sharedContext에 refresh token, token, id 에 대한 getter, setter를 넣어서 step에 대한 모든 중복코드, 파싱 과정 제거했습니다.

## 👍 관련 이슈

- Resolved : #276

2023-09-01 04:27 UTC, yujamint requested changes
고생하셨습니다 주드
리뷰 남긴 거 확인 부탁드려요~

2023-09-01 04:27 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/MemberSteps.java
> +            SharedContext sharedContext) {
개행 부탁드려요 ㅋㅋ

2023-09-01 04:27 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/ReportSteps.java
> +        Long reportedMemberId = (Long) sharedContext.getParameter(reportedMember);
이거 `getId()`로 가져올 수 있나요?? 그렇다면 id는 모두 `getId()`로만 가져오는 게 일관성 있을 거 같아요

2023-09-01 04:27 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/ApplySteps.java
> +        Long memberId = (Long) sharedContext.getParameter(memberName);
`getId()` 쓰면 될 거 같아요

2023-09-01 04:27 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/MyStudyFindSteps.java
> +        String memberId = sharedContext.getToken(githubId);
memberId 대신 memberToken이라는 변수명으로 바꾸면 어떨까요?

2023-09-01 04:27 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/StudySteps.java
> +        Long masterId = (Long) sharedContext.getParameter(masterGithubId);
getId() 쓰면 될 거 같아요

2023-09-06 09:12 UTC, CFalws approved these changes

2023-09-06 11:11 UTC, yujamint approved these changes

2023-09-07 04:24 UTC, merged