feat: 모집 중인 스터디 목록 조회
woowacourse-teams/2023-yigongil pull request #39
Opened 2023-07-18 11:24 UTC by CFalws

## 😋 작업한 내용

모집 중인 스터디 목록 조회 기능 추가

## 🙏 PR Point

테스트 최적화 방식!

## 👍 관련 이슈

- Resolved : #30

2023-07-18 14:45 UTC, poi1649 requested changes
JPA의 기능들을 잘 이용해서 적절히 기능을 구현해주신 것 같습니다. 고생많으셨습니다!! 
시간 나실 때 커멘트 확인해주세요!

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +                              .getId();
p4: 저는 get정도는 한 줄에 씁니다. 이런 줄바꿈도 컨벤션으로 정하면 좋겠네요. 🛩️

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/config/auth/MemberArgumentResolver.java
> +        final Nickname nickname = new Nickname("김진우");
p1: final !!!!!!!!!!!!!

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/config/auth/MemberArgumentResolver.java
> +
p1: 공백에 혹시 이유가 있을까요?

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/member/MemberRepository.java
> +    boolean existsByNickname(Nickname nickname);
p5: 원시타입이 아니고 포장한 객체가 파라미터인데도 메서드 작성이 되는군요 신기하네요 🤔

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/member/MemberRepository.java
> +    Member findByNickname(Nickname nickname);
p1: 별다른 이유가 없다면 Optional 로 통일해주는 것이 좋을 것 같아요 !

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +import javax.persistence.*;
P1: import에 와일드카드를 쓰신 이유가 있나요?

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +    public int getCurrentNumberOfMembers() {
p3: `getter 외에는 get을 쓰지 말자`라고 정했었는데, 이 부분은 확실히 애매하네요. 함께 상의해봅시다.

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/roundofmember/RoundOfMember.java
> +import javax.persistence.*;
wildcard2

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/PageStrategy.java
> +public enum PageStrategy {
p5: 👍

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/PeriodUnit.java
> +    private static final Pattern pattern = Pattern.compile("^[0-9]+[dDwW]$");
p5 : 정규식 한 번만 컴파일👍

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/PeriodUnit.java
> +        if (!pattern.matcher(input).matches()) {
p4: 부정형을 긍정형으로 변경하고 if문 안에서 return 을 하는 방향이나 메서드를 분리해도 좋을 것 같아요

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +import javax.persistence.*;
3

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyRepository.java
>      Study save(Study study);
p3: member는 find -> save 순인데 여기는 save -> find 순이네요.  저는 CRUD 순으로 정렬하는데 혹시 기준이 있으신가요?

2023-07-18 14:45 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +    @GetMapping(path = "/recruiting")
p2: `path` 를 써줄지 말지도 저희 팀끼리 통일하면 좋을 것 같아요

2023-07-18 14:45 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/SharedContext.java
> +    private ExtractableResponse<Response> response;
p3: 검증을 위해서군요 👍 그런데 SharedContext 만으로는 뜻이 명확하지 않아서 ResponseSharedContext 식으로 명확하게 바꿔주면 더 좋을 것 같아요. 추후 여러가지 정보를 SharedContext를 통해 공유할 것 같아 미리 구별을 해놓으면 유지보수에 편하지 않을까 싶습니다.

2023-07-18 14:45 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/SharedContext.java
> +    }
p1: getter, setter, getter, setter 순서보다는 getter와 setter를 서로 붙여주는게 좋지 않을까요?

2023-07-18 14:45 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/StudySteps.java
> +        assertThat(recruitingStudyResponses).hasSize(PageStrategy.Constants.PAGE_SIZE);
p2: 현재는 PAGE_SIZE가 1이라 테스트가 통과하지만, 추후 현재 모집중인 스터디가 요청한 PAGE_SIZE보다 작다면 테스트가 실패하겠네요. 
결과의 size는 page_size보다 작거나 같다 정도로 size를 검증하고, 
결과의 ProcessingStatus가 모두 Recruiting인지 추가로 검증해주면 좋지 않을까요?

2023-07-18 14:45 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/StudySteps.java
> +    public void 모집중인스터디를확인할수있다() {
p1: 메서드 이름에 언더바 붙여주세요 !! 😄

2023-07-18 14:45 UTC, poi1649 commented on backend/src/test/java/com/yigongil/backend/domain/study/PeriodUnitTest.java
> +        // given
p4: given과 when 사이에 아무것도 없을 때, 원래 띄워주시나요? 저는 두 개를 붙여서 쓰는 편인데 이것도 상의 후 통일하는 편이 좋겠네요 ! 👍

2023-07-18 17:11 UTC, yujamint requested changes
고생하셨어요 에밀~ 몇가지 궁금한 점에 대해 질문, 코멘트 남겼으니 확인 부탁드립니다

2023-07-18 17:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/config/auth/MemberArgumentResolver.java
>      public Object resolveArgument(final MethodParameter parameter, final ModelAndViewContainer mavContainer,
p2: ArgumentResolver는 각각 다르게 구현되어 있는 것 같은데, 주드가 작업한 코드로 통일하면 좋을 것 같아요~ (현재 BE/develop 브랜치 코드)

2023-07-18 17:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/member/MemberRepository.java
> +    Member findByNickname(Nickname nickname);
포이 의견에 동의합니다!

2023-07-18 17:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/member/MemberRepository.java
>  public interface MemberRepository extends Repository<Member, Long> {
p5: Repository 메서드 배치 방식을 CRUD 순서대로 해도 좋을 것 같다는 생각이 드네요. 팀원 다 함께 있을 떄 얘기 나눠보죠!

2023-07-18 17:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +    public int getCurrentNumberOfMembers() {
p4: 포이의 의견에 더해 남겨보자면, Collection.size() 메서드와 같이 `sizeOfCurrentMembers()` 같은 네이밍은 어떨까 싶어요.

2023-07-18 17:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/PageStrategy.java
> +public enum PageStrategy {
p5: 질문 남깁니다! `PageStrategy`는 애플리케이션에서 사용될 수 있는 페이징 방식을 정의해 놓는 Enum 타입인 건가요??

2023-07-18 17:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/PageStrategy.java
> +public enum PageStrategy {
p3: size는 사용자에게 입력 받는 것이 적합해 보이는데, Enum으로 관리되는 이유가 있을까요?

2023-07-18 17:11 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +    public ResponseEntity<List<RecruitingStudyResponse>> readRecruitingStudies(int page) {
p2: API 명세를 확인했을 때, `GET /v1/studies/recruiting?page=0&size=3&sort=date` 와 같은 URI를 가집니다. 즉, page와 size, sort 모두 입력받는 것으로 확인됩니다. 컨트롤러 메서드는 이와 다른 형태로써 존재하는 이유가 있을까요?? API 명세가 바뀐 것일까요??

2023-07-18 17:11 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/SharedContext.java
> +    private ExtractableResponse<Response> response;
p5: 저는 Request와 Response 외에 어떤 정보가 추가로 공유될지 잘 생각이 안 나는군요.. 그래서 당장은 request와 response 모두 하나의 클래스에서 관리해도 좋을 것 같다는 생각도 들어요. 오히려 클래스를 분리함으로써 복잡도가 늘어날 수도 있을 것 같아요!

2023-07-19 01:53 UTC, kevstevie approved these changes
리뷰가 고봉밥이라 쓸게 없네요 저는 approve하겟습니다

2023-07-19 01:53 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +    @GetMapping(path = "/recruiting")
mapping에서 파라미터가 한개인 부분은 path 안붙여줘도 될 것 같아요

2023-07-19 02:28 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/config/auth/MemberArgumentResolver.java
> +        final Nickname nickname = new Nickname("김진우");
이건 나중에 BE/develop과 머지할 때 기존 코드를 사용하는 방식으로 하면 될 거 같아서 러프하게 구현했습니다~

2023-07-19 03:47 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +import javax.persistence.*;
설정의 문제인  거 같네요!

2023-07-19 03:49 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/round/Round.java
> +    public int getCurrentNumberOfMembers() {
굿입니다~

2023-07-19 03:56 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/study/PageStrategy.java
> +public enum PageStrategy {
네엡 맞습니다~ size를 입력받는 것이 좋을 거 같기는 한데 우리 안드로이드 크루가 페이지 번호만 넘기는 방식을 생각하셨다고 해서 저도 그렇게 구현했어요!

2023-07-19 03:57 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/study/PeriodUnit.java
> +        if (!pattern.matcher(input).matches()) {
저는 부정형을 쓰는 걸 더 선호해서 이렇게 구현했는데요 개인차가 있을 거 같네요!

2023-07-19 03:57 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyRepository.java
>      Study save(Study study);
딱히 기준은 없습니다. crud 순으로 하는 것도 좋을 거 같아요~

2023-07-19 03:58 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +    @GetMapping(path = "/recruiting")
좋습니다 ~

2023-07-19 04:00 UTC, CFalws commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/SharedContext.java
> +    private ExtractableResponse<Response> response;
한 번 얘기해보는 것도 좋을 것 같아요! 저도 추후에 복잡도가 올라갔을 때 수정하는 것이 더 좋아보이네요

2023-07-19 04:01 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +    public ResponseEntity<List<RecruitingStudyResponse>> readRecruitingStudies(int page) {
네! api 명세가 변경되어서 변경된 방식으로 구현했습니다

2023-07-19 04:29 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/config/auth/MemberArgumentResolver.java
> +
이건 변경될 부분이라 그대로 뒀고 리베이스 통해 수정했습니다!

2023-07-19 04:29 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/member/MemberRepository.java
> +    Member findByNickname(Nickname nickname);
좋아요~

2023-07-19 04:41 UTC, poi1649 approved these changes

2023-07-19 04:42 UTC, yujamint approved these changes
Cool.

2023-07-19 04:53 UTC, merged