티어 계산 및 경험치 계산 로직 구현
woowacourse-teams/2023-yigongil pull request #397
Opened 2023-09-05 07:55 UTC by poi1649

## 😋 작업한 내용

기획 회의를 바탕으로 티어 계산 및 경험치 계산 로직 구현

## 🙏 PR Point

경험치 관리 부분

## 👍 관련 이슈

- Resolved : #396

2023-09-09 14:49 UTC, CFalws requested changes
고생하셨습니다~ 
이제 코드 복잡도가 상당히 올라가고 있네요..ㅋㅋ
리뷰하는 게 상당히 힘겨웠습니다
일단 돌아가게 한 후 복잡도가 올라가면 리팩토링 한다는 것이 이상주의가 아니었나하는 생각이 듭니다.
협업을 할 때 다른 사람의 코드를 내 마음대로 수정할 수도 없는 노릇이니까요. 
결국 촉박한 일정에 기능 개발에 우선순위를 두다보면 자연스레 리팩토링은 뒷전이 될 수밖에 없는 거 같아요.
한 번 진지하게 생각을 해봐야겠습니다 ㅎㅎ
좋은 주말 보내시죠들

2023-09-09 14:49 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/member/Tier.java
> +public enum Tier {
한 줄만 띄워주세요~

2023-09-09 14:49 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        List<StudyMember> studyMembers = studyMemberRepository.findAllByStudyIdAndRoleNot(studyId, Role.APPLICANT);
👍

2023-09-09 14:49 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMember.java
> +        member.addExperience(successfulRoundCount * (2 + 1 * study.calculateStudyPeriod()));
1이 의미있는 숫자라면 상수화하는 건 어떨까요?

2023-09-09 14:49 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMember.java
> +        int successfulRoundCount = (int) study.getRounds().stream()
study에게 member를 넘겨주고 successfulRoundCount를 쿼리하는 방식은 어떻게 생각하시나요?

2023-09-09 14:49 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +
경험치 계산 로직이 두 군데에서 (Study, StudyMember) 관리되는 것 같은데 하나로 합치는 건 어떨까요? 
그리고 두 로직의 계산식이 좀 다른 것 같아요
Study
2 + 1 * periodUnit.calcul~ * totalRoundCount

StudyMember::completeSuccessfully
member.addExperience(successfulRoundCount * (2 + 1 * study.calculateStudyPeriod()));

2023-09-09 14:49 UTC, CFalws commented on backend/src/test/java/com/yigongil/backend/fake/FakeController.java
>          return ResponseEntity.ok().build();
👍

2023-09-10 12:31 UTC, yujamint requested changes
포이 주드 구현하느라 고생하셨습니다~ 리뷰가 좀 많이 늦었네요 ㅋㅋㅋ.. 리뷰 남겼으니 확인해 주세요!

2023-09-10 12:31 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/member/Tier.java
> +    }
`upperBoundExperience`가 오름차순으로 잘 정렬되어 있다면 문제 없는 로직이지만, 만약 지금 상태에서 GOLD와 PLATINUM의 순서가 달라진다면, 경험치가 45여도 PLATINUM이 반환되네요.

조금 더 확실하게 가져가기 위해서는 1차 filter 이후에 `upperBoundExperience`가 가장 작은 Tier를 찾는 filter를 하나 더 걸어주는 게 좋을 거 같아요

2023-09-10 12:31 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +            PeriodUnit periodUnit) {
다시 띄워주세요~

2023-09-10 12:31 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        List<StudyMember> studyMembers = studyMemberRepository.findAllByStudyIdAndRoleNot(studyId, Role.APPLICANT);
혹시 이렇게 수정된 이유가 뭔지 알 수 있을까요??
왜 StudyResult.NONE을 대상으로만 조회했는지 궁금해지네요..

2023-09-10 12:31 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +
에밀 리뷰를 보고 확인해 보니, 이 메서드는 현재 테스트 코드에서만 호출되고 있는 거 같아요. 
프로덕션 코드에서 사용되지 않는다면 지우고 `StudyMember.completeSuccessfully()`를 통해서만 관리하는 게 좋을 거 같아요.

2023-09-18 05:17 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +
저희 비즈니스 로직이 변경돼서 더 이상 maximum reward가 필요없게 됐네요! 삭제했습니다👍

2023-09-18 05:18 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMember.java
> +        member.addExperience(successfulRoundCount * (2 + 1 * study.calculateStudyPeriod()));
관리지점이 두개다보니 어디서 상수를 관리해야할지 고민하다가 그냥 커밋했었네요.. 상수화 했습니다!

2023-09-18 05:24 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        List<StudyMember> studyMembers = studyMemberRepository.findAllByStudyIdAndRoleNot(studyId, Role.APPLICANT);
찾아보니 [이 커밋](https://github.com/woowacourse-teams/2023-yigongil/commit/29d37ebb270d176458a42621a05364880a3d8e16#diff-7e14cbc583a1de11a98f316e9864ea77a8a139c9bb12562da090bbc0ef5c4b27) 에서 수정이 일어났는데, 스터디 멤버에 결과를 추가하면서, 중간에 탈주하지 않은 사람을 고려하기 위해 넣었던 걸로 추측되네요..ㅋㅋㅋㅋ

2023-09-18 05:35 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/member/Tier.java
> +    }
날카로운 리뷰네요 
order를 한번 더 검증함으로, 항상 upperBound를 못 넘은 티어 중 제일 작은 티어를 가져오도록 변경했습니👍

2023-09-18 05:41 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMember.java
> +        int successfulRoundCount = (int) study.getRounds().stream()
이런 기본적인 메시지 날리기도 안하고 있었다니.. 바로 수정했습니다.

2023-09-18 14:05 UTC, CFalws approved these changes
수정된 부분 전부 확인했습니다.
고생하셨어요~

2023-09-19 04:27 UTC, yujamint requested changes
리뷰 반영 고생하셨습니다~ 확실히 개선된 점이 보이네요.
그리고 커밋 단위를 나눠준 덕분에 코드 보기가 편했네요. 저도 앞으로 프로젝트 할 때도 커밋을 신경 써야겠다는 생각을 했습니다 ㅋㅋㅋ 어프루브하겠습니다~

2023-09-19 04:28 UTC, yujamint approved these changes
아 실수로 request changes 했네요 어프루브하겠습니다 ㅋㅋ

2023-09-19 04:35 UTC, merged