피드 기능을 구현한다.
woowacourse-teams/2023-yigongil pull request #418
Opened 2023-09-13 07:56 UTC by poi1649

## 😋 작업한 내용

피드 작성 / 조회 기능 구현
인증 작성 / 조회 기능 구현

## 🙏 PR Point

1. 피드 조회시 페이지네이션 어떤 걸 이용하는 게 좋을까요
2. 현재는 피드를 확인 / 작성 시 해당 스터디원인지 조회 기능이 없습니다. 이에 대해 공통 관심사를 AOP 또는 filter로 분리하고 싶은데 의견 부탁드립니다.

## 👍 관련 이슈

- Resolved : #404

2023-09-14 02:11 UTC, kevstevie requested changes
안녕하세요 포이
구현이 참 빠르네요
join 전략 사용에 대한 부분은 고민을 더 해봐야할 것 같아요
해당 스터디원인지 검증하는 부분은 대부분의 로직에서 필요한데 aop로 만들면 좋을 것 같긴 하네요
이 부분에 대해서 대략적인 구상을 보여주시면 좋을 것 같습니다

2023-09-14 02:11 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +            RegularFeedPostRepository regularFeedPostRepository
p2: feed service로 분리하는 건 어떤가요??

2023-09-14 02:11 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +                                                              .content(request.content())
p3: 인증 피드에 어떤 round인지 필요한 이유가 궁금합니다

2023-09-14 02:11 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/domain/roundofmember/RoundOfMember.java
>      }
p2: completeRound에서 직접 update 해주거나 update~ 메서드를 private으로 해주면 좋을 것 같습니다

2023-09-14 02:11 UTC, kevstevie commented on backend/src/test/resources/features/feed.feature
> +    Given "jinwoo"가 이름이 "자바1"인 스터디를 시작한다.
p1: 시작 전엔 작성할 수 없다는 테스트가 추가되면 좋을 것 같습니다

2023-09-14 02:11 UTC, kevstevie commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +                                                     .equals("FeedPost"))
조금 어지러운데 방법을 찾아보죠

2023-09-14 02:11 UTC, kevstevie commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        Page<FeedPost> feedPosts = feedPostRepository.findAllByStudyId(studyId, pageable);
p5: 검색 기능이 생긴다면 slice를 통한 no offset이 좋을 것 같은데 아직 미정이니 이대로 가시죠

2023-09-14 02:35 UTC, yujamint requested changes
포이 고생하셨어요 DatabaseCleaner만 어떻게 해결하고 싶네요
고생하셨슴다

2023-09-14 02:35 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +            FeedPostRepository feedPostRepository, CertificationFeedRepository certificationFeedPostRepository,
p2: 개행해 주세요~

2023-09-14 02:35 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +                                                              .study(study)
p4: 별 문제는 아니지만, 코드 일관성을 위해 createRegularFeedPost()와 비슷한 형태로 수정하면 어떨까요??

```suggestion
    public void createCertificationFeedPost(Member member, Long studyId, CertificationFeedPostCreateRequest request) {
        CertificationFeedPost feedPost = CertificationFeedPost.builder()
                                                              .author(member)
                                                              .study(findStudyById(studyId))
```

2023-09-14 02:35 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +                                                     .equals("FeedPost"))
p3: 특정 엔티티가 특정 클래스를 상속하고 있는지 검사하는 메서드로 분리해도 좋을 거 같네요~
`public boolean isSubClassOf(Class class)` 이런 시그니처로요.

근데, 사실 `BaseEntity`를 상속하고 있는지 여부 하나로만 검사해도 다 통과했으면 좋겠네요. 
지금 생각나는 방법으로는 superClass를 재귀적으로 돌면서 `Object.class` 또는 `null`이 나올 때까지 검사하는 방법이 있을 거 같아요.
(`BaseEntity.class.isAssignableFrom(entityType.getClass()`)으로 시도해봤는데 이건 왜인지 안 되네요)

+) 사실 급한 문제는 아니니 포이 의견에 따라 넘어가도 좋습니다

2023-09-14 02:35 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/FeedSteps.java
> +               .contentType("application/json")
```suggestion
               .contentType(MediaType.APPLICATION_JSON_VALUE)
```

2023-09-14 02:35 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/FeedSteps.java
> +               .contentType("application/json")
```suggestion
               .contentType(MediaType.APPLICATION_JSON_VALUE)
```

2023-09-17 09:23 UTC, CFalws approved these changes
aop가 복잡도를 너무 높이지 않을까 우려됩니다만 한 번 시도해보는 것도 좋을 거 같네요. 
그리고 현재 Study -> Round -> RoundOfMember -> certification로 이어지는 연관관계를 어느 단계에서는 끊어야 할 거 같습니다. 
Study에서 모든 도메인 로직을 다 처리하게 되는 이유가 계속 깊어지는 연관관계 때문이라고 생각이 듭니다. 
고생 많으셨습니다~

2023-09-17 13:49 UTC, yujamint requested changes
포이 고생하셨습니다~ 얘기 나누고 싶은 부분 리뷰 남겼으니 확인 부탁드려요~

2023-09-17 13:49 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +        return ResponseEntity.ok().build();
p3: FeedPost도 엔티티로, 자원이 생성됐다고 볼 수 있는데 어떠한 자원도 응답하지 않는 이유가 있나요??

Certification을 생성할 때는 Location 헤더에 자원 위치를 응답하는 것과 대조돼서요.

2023-09-17 13:49 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/response/FeedPostResponse.java
> +    public static FeedPostResponse from(FeedPost regularFeedPost) {
p2: 이제 일반/인증 피드 구분이 없어졌으니 변수명도 feedPost로 변경하면 어떨까요?

2023-09-17 13:49 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/FeedService.java
> +    }
p3: 현재 `FeedService`를 `StudyService`에서 참조하고 있습니다. 즉, 서비스 클래스간의 재사용을 의도하신 것 같습니다. 

현재 구조에서 `FeedService`를 재사용하기 좋은 클래스로 만드려면 해당 메서드는 `FeedPost` 도메인 객체를 반환하는 게 좋지 않을까요?
(현재 `CertificationService.findById()`와 같이)

제가 제안드린대로 변경하게 된다면 StudyService를 통해서 FeedService를 다루게 될 텐데, 피드 도메인 자체가 스터디 도메인에 종속적이기 때문에 부자연스럽지는 않은 것 같네요.

2023-09-17 13:49 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/response/MemberCertificationResponse.java
> +                                     roundOfMember.isDone()))
p2: 개행이 필요해 보입니다~

2023-09-17 13:49 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/response/MembersCertificationResponse.java
> +                                                                     roundOfMember.isDone()))
p2: 여기도 개행이 필요해 보이네요

2023-09-17 13:49 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/FeedSteps.java
> +                                                              .contentType("application/json")
p3: `MediaType.APPLICATION_JSON_VALUE`를 사용하는 게 좋을 거 같네요!

2023-09-17 13:49 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +            int page
p4: 궁금한 게 있습니다~ API 명세 회의 당시에 페이징에 필요한 `oldestPostId`라는 쿼리스트링에 대해서 고민을 했었는데요. 이 부분 어떻게 정한 건지 알 수 있을까요??

2023-09-18 06:26 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/response/FeedPostResponse.java
> +    public static FeedPostResponse from(FeedPost regularFeedPost) {
오.. 꼼꼼하시네요 민트 클래스 이름도 전체적으로 수정했습니다

2023-09-18 06:37 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/FeedService.java
> +    }
이 부분이 조금 고민이 되는데

1. 서비스 계층을 다음 두 단계로 엄격하게 분리한다. 
     - controller와 맞닿는 계층, response를 반환함
     - Service안에서만 작동하는 계층, 도메인을 반환함
2. 서비스 계층을 엄격하게 분리하지 않고, 재사용 가능한 메서드만 도메인을 반환한다.
3. 모든 서비스 계층 메서드가 도메인의 내용을 담은 dto(vo) 를 반환한다. (컨트롤러에서 팩터리 메서드로 가공, 팩터리 메서드 리팩토링필요)
4. 모든 서비스 계층 메서드가 도메인을 반환한다. (컨트롤러에서 response.from 같은 팩터리 메서드로 가공)

이 정도 선택지가 있을 것 같아요. 

1번은 응집성을 확실하게 지킬 수 있는 가능성이 높지만, 현재 스터디 서비스처럼 직접 도메인을 가공하는 친구들을 별도의 서비스로 분리해줘야만 명확한 사용이 된다.

2번은 제일 수정점은 적지만, 매번 다른 서비스의 메서드를 확인해야한다는 단점이 있다.

3번은 이상적이지만 리팩터링 비용이 높다.

4번은 수정점도 적고, 재사용 가능성도 높아진다. 

저는 민트 의견대로 1번을 선택하려면 도메인의 애그리거트 루트 정리를 확실하게 하고 루트에서만 컨트롤러에 맞닿도록 해야할 것 같아요.

2023-09-18 06:40 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +        return ResponseEntity.ok().build();
Certification 같은 경우는 확실하게 단 건 조회가 일어나지만, Feed는 단건조회가 일어나지 않을 것 같아 그대로 놔뒀네요. open api 를 만드는게 아니니 rest의 규약을 다 따를 필요는 없겠다고 생각했습니다.

2023-09-18 07:29 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/ui/StudyController.java
> +            int page
기존 코드가 전부 Pageable로 되어있어서 통일성을 위해 임시로 작성했습니다. 그런데 이거부터라도 바꿔놓는게 좋을 것 같네요

2023-09-20 07:19 UTC, kevstevie approved these changes

2023-09-20 07:30 UTC, yujamint approved these changes
포이 답변 잘 들었습니다 감사합니다~ 고생하셨어요 어프루브할게요!

2023-09-20 11:14 UTC, merged