[홈 탭] 서버통신 구현 및 DI 적용
woowacourse-teams/2023-yigongil pull request #429
Opened 2023-09-20 12:59 UTC by s9hn

## 😋 작업한 내용

- DI, Flow를 적용해보았읍니다

## 🙏 PR Point
- Cold Flow로 서버통신을 구현하였는데, 
- 현재 뷰는 도메인모델을 알고있습니다. 왜와이?
- 뷰모델은 어떠한 뷰에도 종속된 모델이 아니기때문에, 서버통신 후 얻은 리스폰스모델을 들고만 있고.
- 해당 모델을 사용하려는 뷰에서, 그 도메인모델을 가져와 uiState(모델)로 래핑해서 사용합니다!
- 이렇게 될 경우, 뷰가 수정되어도 뷰모델까지 수정사항이 전파되지 않습니다.
- 이견 반박 태클 다 받습니다 컴온

## 👍 관련 이슈

- Resolved : #

2023-09-20 12:59 UTC, no1msh approved these changes
LGBT

2023-09-20 18:32 UTC, inseonyun requested changes

2023-09-20 18:32 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/data/mapper/HomeMapper.kt
> +}
it도 study로 변경해서 하면 읽기 좋을 거 같아요
```kotlin
this.studies.map { study ->
...
}
```

2023-09-20 18:32 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        binding.rvHome.setHasFixedSize(true)
rvHome의 아이템 스터디 리스트 뷰는 정말 고정된 사이즈를 갖나요?? 
[SetHasFixedSize 관련 Stackoverflow](https://stackoverflow.com/questions/28709220/understanding-recyclerview-sethasfixedsize)

2023-09-20 18:32 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/home/HomeViewModel.kt
> +    val uiState: StateFlow<HomeUiState> get() = _uiState
헉헉 Flow에 대해 설명해주세요 
그리고 왜 AAC 가 아닌 Flow를 택했나요?
AAC로는 안 되나요??

2023-09-20 18:32 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/home/adapter/HomeAdapter.kt
>                      return oldItem == newItem
이전 리뷰 참고
[이전 리뷰](https://github.com/woowacourse-teams/2023-yigongil/pull/425#discussion_r1332006601)

2023-09-21 01:49 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/presentation/home/HomeViewModel.kt
> +        ) : HomeUiState
오옹... UiState는 보통 이런 구조인가요?
상태가 정보를 데이터를 들고 있는 형태

2023-09-21 01:50 UTC, RightHennessy commented on android/app/src/main/java/com/created/team201/data/mapper/HomeMapper.kt
> +            grassSeed = it.grassCount
둘의 이름이 다르네요.. 
ui에서 사용되는 이름을 ui 쪽에 맞춰 네이밍 하는게 맞을까요?
저도 이런 네이밍을 선호했었는데 유지보수할 때 굉장히 불편하더라고요..

2023-09-21 05:24 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/home/HomeFragment.kt
> +        binding.rvHome.setHasFixedSize(true)
holy-moly 저도 저거 ㅁ궁금했던건데 감사합니다 
당장지우겟습니다

2023-09-21 05:31 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/home/HomeViewModel.kt
> +        ) : HomeUiState
맞읍니다 오늘배웠쮸?

2023-09-21 05:31 UTC, s9hn commented on android/app/src/main/java/com/created/team201/data/mapper/HomeMapper.kt
> +            grassSeed = it.grassCount
넹~묜

2023-09-21 07:52 UTC, inseonyun approved these changes
LG Elec.~

2023-09-21 07:52 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/data/repository/DefaultHomeRepository.kt
> +        homeService.getUserStudies().map { it.toUserStudy() }
it ..... 


is Study..

2023-09-21 07:55 UTC, RightHennessy commented on android/app/src/main/res/layout/fragment_home.xml
> +            name="vm"
아하 @!

2023-09-21 07:55 UTC, RightHennessy approved these changes
구웃 고생했습니다 ^_^

2023-09-21 07:56 UTC, merged