refactor: 피드 조회시에 스터디 이름도 반환
woowacourse-teams/2023-yigongil pull request #454
Opened 2023-09-23 02:57 UTC by kevstevie

## 😋 작업한 내용

refactor: 피드 조회시에 스터디 이름도 반환

## 🙏 PR Point

[변동사항 참고](https://github.com/woowacourse-teams/2023-yigongil/issues/453)

## 👍 관련 이슈

- Resolved : #453

2023-09-23 03:40 UTC, poi1649 requested changes
주말도 열일 하시네요. 고생많으십니다. 그런데 이 정보 피드 게시글을 줄때마다 줄 정보는 아닌 것 같아서, 그냥 클라단에서 이전 정보 가져오던가, 인증정보 줄 때 주는게 더 자연스러워보여요. 
페이지네이션 떄문에 다른 페이지 줄 때마다 스터디 이름을 주게 되는건 별로 같습니다

2023-09-23 03:45 UTC, kevstevie commented
음 확실히 페이지네이션을 생각못했네요
클라단에서 가져오는거보단 서버에서 반환하는게 좋아보이는데 더 좋은 방법 없을까요

2023-09-23 08:21 UTC, yujamint approved these changes
피드 뷰로 이동했을 때 호출되는 API가 [스터디 멤버 인증 정보 조회](https://www.notion.so/eed129cdec1544d9b999f932967a1507?pvs=4)와, [피드 목록 조회](https://www.notion.so/d6233d568ec840cd930569f3addcf61d?pvs=4) 맞죠?

만약 스터디 이름을 주기 위해 API를 하나 더 추가할 것이 아니라면, StudyName을 두 API 중 하나에 껴서 넣어줘야 합니다. 그렇다면 저도 해당 뷰에 들어왔을 때 무조건 한 번만 호출되는 `인증 정보 조회 API`를 통해 전달되는 것이 자연스러워 보입니다~

포이 말처럼 `피드 목록 조회 API`는 피드 뷰 내에서도 여러 번 호출되는 API라는 점에서 이러한 의견 드립니다~ 그렇게 된다면 기존의 서비스 메서드도 로직 변경 없이 Response DTO만 바뀌면 될 것 같아요.

일단 포이 Request Changes랑 같은 내용이기 때문에 어프루브 하겠습니다. 고생하셨어요 주드~

2023-09-25 04:47 UTC, poi1649 approved these changes

2023-09-25 04:47 UTC, merged