refactor: 초안
woowacourse-teams/2023-yigongil pull request #462
Opened 2023-09-29 12:11 UTC by kevstevie

## 😋 작업한 내용

일단 초안인데요

저희 이거 할 수 있는거 맞나요?
필드를 인터페이스로 나누는건 불가능하고 결국 상속으로 V1 V2를 만드는게 최선같은데 확장성이 있는지 의문이..
일단 V1 V2 구분하고 테스트/컴파일 가능하게 해놨는데 결국 response도 두개를 만들거나 둘다 포함한 response로 바꿔야 할 것 같고 결국엔 service도 분리해야될 것 같은데 쉽지 않네여 

## 🙏 PR Point

- 

## 👍 관련 이슈

- Resolved : #

---

## 기획의 어떤 부분을 구현 / 수정했는가 (굉장히 상세하게 적어주세요, 해당 커밋의 링크, 코드의 위치를 남겨주면 더욱 좋습니다.)

밑은 예시입니다.

**[시작되면서 스터디의 주 몇 회 정보를 유저가 실제로 선택한 일 수로 수정](http://관련기획링크)**
  - StudyService의 createStudy 메서드에서 PeriodOfRound 를 받지 않도록 수정했습니다. [해당커밋](http://커밋링크)
  - Study의 start 메서드에서 파라미터로 시작한 날짜를 받도록 구현하였습니다.
  - 날짜(월화수목금토일)를 뜻하는 Enum을 Study 패키지에 추가하였습니다.
  - flyway에서 해당 엔티티에 필요할 칼럼을 수정했습니다.

**[스터디가 더 이상 종료되지 않도록 수정](http://관련기획링크)**
  - 상동

2023-09-30 10:54 UTC, yujamint requested changes
주드 연휴에도 고생하셨습니다. 
이번 리팩토링은 규모가 너무너무 큰 작업이 맞는 거 같습니다... 그래서 어떤 목적,방향으로 코드를 봐야 하는지에 대해서도 좀 의문이 생겼던 리뷰네요. 그래서 일단은 기획적인 부분과 컨벤션 관련된 부분으로 봤습니다.

일단 저도 상속을 통해서 해결하는 거에는 찬성합니다. 뾰족한 수가 안 보이네요. 당장은 빠르게 진행할 수 있는 방식을 선택하는 게 좋아보여요. 많은 클래스가 2개로 나뉘겠지만요...

그리고 아직 본격적인 코드 작업에 착수하기 이르다는 생각도 드네요.
일단 버전을 높이면서 상황 별로 어떻게 대응할 것인지에 대한 룰을 정해야 할 거 같아요.
그리고 그에 따라 리팩토링도 점진적으로 할 수 있도록 어떤 부분을 고쳐야 하는지 명확하게 정할 필요가 있는 거 같아요.
그게 어려운 일이지만요.. 일단 이건 생각해보도록 하죠. 고생하셨습니다~

2023-09-30 10:54 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyV1.java
> +    }
p2: 이 메서드 Study에도 존재하는데, Study에 존재하는 메서드를 protected로 두고 사용하면 어떨까요?

2023-09-30 10:54 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyV1.java
> +    private LocalDateTime startAt;
p3: [슬랙에서 얘기했던 내용](https://201-created.slack.com/archives/C05DYMH3YTZ/p1695708531478359)에 따르면 startAt은 V1, V2 모두 가지고 있어야 할 정보인 거 같아요!

차이점이 있다면 V1은 예상시작일, 진짜 시작일 모두 나타내고, V2는 진짜 시작일만 나타냅니다. 일단 추상 클래스가 갖고 있도록 하는 게 좋을 거 같네요.

2023-09-30 10:54 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/DatabaseCleaner.java
> +                }
p2: 여기 `InhertianceType.SINGLE_TABLE` 인지 확인하는 부분을 boolean 반환하는 메서드로 분리하면 좋을 거 같아요~

2023-09-30 10:54 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyV2.java
> +    private Integer minimumWeek;
p4: 요일에 대한 상태도 가져야 할 거 같은데, 해당 부분은 이번 리팩토링 범위에서 빼고 진행하신 거죠??

2023-10-01 06:30 UTC, poi1649 approved these changes
결국 api에 따른 서비스와 레파지터리 분리는 불가피하다는 생각이 드네요. 지금처럼 최소한의 중복만 제거하고 별도의 클래스로 가는 게 제일 빠른 방법일 것 같습니다. 
연휴에 고생많으셨습니다.

2023-10-01 06:30 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    );
들어갈 파라미터들이 스터디의 구현체별로 다를 수 있을 것 같아요. 이에 대해 각각의 수정 메서드를 놓는 경우가 더 적합하겠다 싶긴한데.. api의 수정도 있고하니, 날짜 수정만 별도의 메서드로 분리하는건 어떨까요

2023-10-04 05:55 UTC, kevstevie commented
안녕히 계세요 여러분!!

2023-10-04 05:55 UTC, closed without merging