Be/feature/452
woowacourse-teams/2023-yigongil pull request #466
Opened 2023-10-04 11:45 UTC by CFalws

## 😋 작업한 내용

- 

## 🙏 PR Point

- 

## 👍 관련 이슈

- Resolved : #

---

## 기획의 어떤 부분을 구현 / 수정했는가 (굉장히 상세하게 적어주세요, 해당 커밋의 링크, 코드의 위치를 남겨주면 더욱 좋습니다.)

밑은 예시입니다.
[이슈 링크](https://github.com/woowacourse-teams/2023-yigongil/issues/452)
  - Round의 진행 요일을 추가하지는 않았습니다. 다만, 날짜를 계산해서 Round에 endAt을 넣어주는 것이 더 낫지 않을까 하는 생각이었는데 좋은 의견 있다면 주세요~! 
  - Study에 minimumWeeks를 추가하였습니다. 해당 필드가 최소 진행 주차를 표현하게 됩니다. 
  - 날짜를 int 자료형으로 표현하였습니다. 
  - flyway에서 기존 column을 drop하고 새로운 칼럼을 추가하였습니다. 다만 컴파일 에러가 많아서 실제 디비 서버에 적용해보지는 못했습니다. 
  - 스터디와 진행 요일의 매핑 테이블을 composite key로 식별케 하였습니다.

2023-10-04 17:37 UTC, yujamint requested changes
에밀 고생하셨습니다~ 궁금한 부분이 좀 있어서 질문 몇 가지 남겼습니다. 답변 주시면 감사하겠습니다~

2023-10-04 17:37 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    protected void validateStudyProcessingStatus() {
p2: V1,V2를 없앴으니 접근제어자가 private이어도 좋을 거 같습니다!

2023-10-04 17:37 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    public static Study initializeStudyOf(
p3: 빌더, update 메서드를 비롯하여 `minimumWeeks`의 값이 할당되는 부분이 없는 이유는 너무 변경지점이 많아서 일단 보류한 것인가요??

2023-10-04 17:37 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    private int minimumWeeks;
p5: 뭔가 속이 시원한데요 ㅋㅋ

2023-10-04 17:37 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    protected void updateInformation(Member member, String name, Integer numberOfMaximumMembers, LocalDateTime startAt, String introduction) {
p2: 이 메서드도 private이어도 될 거 같습니다!

2023-10-04 17:37 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/ProgressDayOfWeek.java
> +    @EmbeddedId
p3: 이렇게 복합키를 사용할 수 있는 줄은 처음 알았네요 👍
엔티티의 id로 쓰인다는 점에서 클래스명을 `ProgressDayOfWeekId`로 바꾸는 게 더 직관적일 거 같은데 어떻게 생각하시나요??

2023-10-04 17:37 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/ProgressDayOfWeekKey.java
> +    private int progressDayOfWeek;
p3: 이게 스터디를 주 몇 일 하는지 나타내는 값인가요?? 왜 복합키로 사용한 건지 궁금합니다!

2023-10-05 02:53 UTC, poi1649 approved these changes
고생많으셨습니다 에밀 
이 녀석을 dev에 봉합시키는 순간 말도안되는 문제들이 생기겠군요. git 이 없었다면 정말 걱정됐을 것 같아요ㅋㅋㅋㅋㅋㅋ.
api 만들면서 하나씩 해결해보죠! 컴파일 에러 처리반 TEAM 201 화이팅입니다

2023-10-05 02:53 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    public static Study initializeStudyOf(
민트의 코멘트를 보고 빌더가 있는데 왜 이걸 이렇게 썼지? 생각해보니 Period와 Round를 문자열만 받아 생성하기 어려워서였군요ㅋㅋㅋ.. 두 객체에 문자열을 받아 생성할 수 있는 책임을 넘겨주고 빌더에 .period(new Period(PeriodOfRound)) 처럼 스트링을 넘겨주는 편이 좋아보이는데 이때는 왜 이렇게 했을까요??

2023-10-05 02:53 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +        this.introduction = introduction;
update도 이렇게 말고 변수마다 구현해줄 걸 그랬네요ㅋㅋㅋㅋㅋ.. 단일 책임 원칙을 경험에서 배워갑니다.

2023-10-05 02:53 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +                             .introduction(introduction)
이친구는 삭제가 필요하겠군요

2023-10-05 02:56 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    private Integer progressDaysPerWeek;
Enum set으로 두는 건 어떨까요?

2023-10-05 03:03 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    private int minimumWeeks;
객체도 지워버리시죠

2023-10-05 05:03 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/Study.java
> +    public static Study initializeStudyOf(
우린 확실히 뉴비였네요

2023-10-15 05:05 UTC, yujamint approved these changes

2023-10-15 05:08 UTC, merged