refactor: 인증 조회 방식 수정
woowacourse-teams/2023-yigongil pull request #520
Opened 2023-10-18 12:21 UTC by kevstevie

## 😋 작업한 내용

인증 조회 방식을 바꿨습니다
roundid와 memberid로 찾아서 조회합니다

## 🙏 PR Point

- 

## 👍 관련 이슈

- Resolved : #517

---

## 기획의 어떤 부분을 구현 / 수정했는가 (굉장히 상세하게 적어주세요, 해당 커밋의 링크, 코드의 위치를 남겨주면 더욱 좋습니다.)

밑은 예시입니다.

**[시작되면서 스터디의 주 몇 회 정보를 유저가 실제로 선택한 일 수로 수정](http://관련기획링크)**
  - StudyService의 createStudy 메서드에서 PeriodOfRound 를 받지 않도록 수정했습니다. [해당커밋](http://커밋링크)
  - Study의 start 메서드에서 파라미터로 시작한 날짜를 받도록 구현하였습니다.
  - 날짜(월화수목금토일)를 뜻하는 Enum을 Study 패키지에 추가하였습니다.
  - flyway에서 해당 엔티티에 필요할 칼럼을 수정했습니다.

**[스터디가 더 이상 종료되지 않도록 수정](http://관련기획링크)**
  - 상동

2023-10-18 12:31 UTC, poi1649 requested changes

2023-10-18 12:31 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        Certification certification = certificationService.findByRoundIdAndMemberId(roundId, memberId);
optional 로 받고 예외처리를 해주면 좋지 않을까요?

2023-10-18 12:31 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/CertificationService.java
>          return certificationRepository.findById(id);
이거 이제 안쓰지 않나요?

2023-10-19 01:53 UTC, yujamint approved these changes

2023-10-19 02:05 UTC, poi1649 approved these changes

2023-10-19 02:06 UTC, merged