[AN] 온보딩뷰 수정사항 반영
woowacourse-teams/2023-yigongil pull request #586
Opened 2023-10-26 11:30 UTC by inseonyun

## 😋 작업한 내용

- 닉네임 중복체크 실시간(입력 하나하나에 대해 서버 통신)
- 닉네임 입력 뷰 디자인 변경

## 🙏 PR Point

https://github.com/woowacourse-teams/2023-yigongil/assets/84364741/717faecb-019a-47b8-9e67-95787525a50d
 

## 👍 관련 이슈

- Resolved : #573

2023-10-27 01:32 UTC, no1msh approved these changes
Good

2023-10-27 07:18 UTC, s9hn approved these changes
음 머 리뷰할게 없쿤요 ! 추후에 스플로 리팩하면 될듯 ! SKTM

2023-10-28 12:58 UTC, inseonyun commented
수정 사항
- LiveData State Flow / Shared Flow로 변경
- EditText Nickname 검증 EditText 입력 시 마다 매번 검증 하는 것이 아닌 debounce로 0.7초 간 입력이 없을 경우 닉네임 검증
- NicknameUiModel은 MyPage에서도 쓰고 있어서 추후 MyPage 리펙터링 할 때 없애도록 하겠습니다.

조금 찝찝한 거 
- 필수 입력이 모두 입력이 되면 버튼의 enable을 변경하고, 그 버튼을 누르면 결과에 따라 Toast / startActivity 하게 하려고 하는데 Event에 showToast / startActivity / Enable  이렇게 두고 관리하려고 하는데 viewModel init에서 필수 입력 combine - collect 해서 Event SharedFlow 값 바꿔주는 방식이 어색함

2023-10-28 13:05 UTC, s9hn approved these changes

2023-10-28 13:05 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
>      private fun initBinding() {
이제 보내줘도 될 것 같습니다

2023-10-28 13:05 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingViewModel.kt
> +                _onBoardingEvent.emit(Event.EnableSave(isEnable))
함수이름과 다르게 뷰모델에서 emit하는 구조가 좀 이상한 것 같습니다!

뷰모델에 stateFlow가 있는데도 불구하고 emit을 해줘야하는지 의문입니다.

뷰모델은 state를 업데이트시키고, 뷰에서 꺼내서 쓰는식으로 바꿀순 없을까요?

2023-10-28 13:05 UTC, s9hn commented on android/app/src/main/res/layout/activity_on_boarding.xml
>  <layout xmlns:android="http://schemas.android.com/apk/res/android"
데이터바인딩 지워주십쇼!

2023-10-28 13:05 UTC, s9hn commented on android/app/src/main/res/layout/activity_on_boarding.xml
>              android:onClick="@{() -> viewModel.patchOnBoarding()}"
22

2023-10-28 13:05 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingViewModel.kt
> +        class EnableSave(val isEnable: Boolean) : Event
class인 이유가있나요?

2023-10-28 13:07 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingViewModel.kt
> +        class EnableSave(val isEnable: Boolean) : Event
isEnable을 생성자로 받아 프로퍼티로 사용하고자 class로 뒀습니당

2023-10-28 13:07 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingViewModel.kt
> +                _onBoardingEvent.emit(Event.EnableSave(isEnable))
도전-!

2023-10-28 13:10 UTC, s9hn requested changes
저는 sharedFlow가 왜 필요한지 모르겠습니다!
stateFlow로 충분히 가능해보입니다

2023-10-28 13:10 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +            viewModel.onBoardingEvent.collect { event ->
collect 내부에서 while돌고있어서 수집 중단안됩니다. collect 스코프아래에 로그찍어도 안나옵니다

2023-10-28 13:14 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingViewModel.kt
> +        class EnableSave(val isEnable: Boolean) : Event
ㅋㅋvalue class되나했는데 inner로는 못쓰네요
data class 어떠신가여

2023-10-28 13:22 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +            viewModel.onBoardingEvent.collect { event ->
헉

2023-10-28 13:27 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +            viewModel.onBoardingEvent.collect { event ->
Event에 관한 처리는 StateFlow보단 SharedFlow가 맞지 않을까요?

2023-10-28 13:41 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +            viewModel.onBoardingEvent.collect { event ->
으으으음 저도 다시생각해보니 맞는것같네요

버튼 활성, 비활성화는 - stateFlow로 처리하고
버튼클릭했을 때 뷰모델의 stateFlow를 통해 특정 이벤트를 emit하는식으로 !
맞나유?

2023-10-29 12:04 UTC, inseonyun commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +            viewModel.onBoardingEvent.collect { event ->
launch scope 두 개 열어서 collect 해주는 방식으로 수정했슴다
추가적으로 아래처럼 변경할까 고민을 해봤었는데 어떤 방식이 보기 좋아보이나용?
```kotlin
private fun collectViewModelFlows() {
        repeatOnStarted {
            launch {
                collectOnBoardingEvent()
            }
            launch {
                collectNicknameState()
            }
        }
    }

    private suspend fun collectOnBoardingEvent() {
        viewModel.onBoardingEvent.collect { event ->
            when (event) {
                ShowToast -> showToast(getString(R.string.onBoarding_toast_fail))
                SaveOnBoarding -> navigateToMain()
                is EnableSave -> binding.tvOnBoardingBtnSave.isEnabled = event.isEnable
            }
        }
    }

    private suspend fun collectNicknameState() {
        viewModel.nicknameState.collect { nicknameState ->
            binding.tvOnBoardingNicknameValidateIntroduction.text =
                getString(nicknameState.introduction)
            binding.tvOnBoardingNicknameValidateIntroduction.setTextColor(
                getColor(
                    nicknameState.color
                )
            )
        }
    }
```

2023-10-29 14:44 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +            viewModel.onBoardingEvent.collect { event ->
전 걍 깔끔하게 확장함수써서 collect함수 2개만 쓰는게 이뻐보임다 ㅋㅋ

2023-10-29 14:59 UTC, s9hn approved these changes
LGTM!

2023-10-29 14:59 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +    private val binding: ActivityOnBoardingBinding by lazy {
레..아?

2023-10-29 14:59 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingViewModel.kt
> +                }.launchIn(this@launch)
이 부분은 도메인일까 뷰모델의 책임일까 헷갈리네요

2023-10-29 14:59 UTC, s9hn commented on android/app/src/main/java/com/created/team201/presentation/onBoarding/OnBoardingActivity.kt
> +        repeatOnStarted {
확장함수를 좀 더 디테일하게 잡아보는거 어떨까요??
참조 state.collectWithLifecycle {} 과 같이 스코프 한번으로 해결하고싶어요!

2023-10-31 09:46 UTC, merged