내 스터디 목록 조회 기능 추가
woowacourse-teams/2023-yigongil pull request #88
Opened 2023-07-20 13:48 UTC by CFalws

## 😋 작업한 내용

내 스터디 목록 조회 기능

## 🙏 PR Point

## 👍 관련 이슈

- Resolved : #70

2023-07-20 18:09 UTC, yujamint requested changes
에밀 고생하셨습니다! 깔끔하게 잘 짜셨네요. 몇가지 코멘트 남겼으니 확인 부탁드려요~

2023-07-20 18:09 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyRepository.java
> +    List<Study> findStartedStudiesByMember(@Param("member") Member member);
p3: 이 메서드는 '멤버를 기준으로' '시작된' 스터디를 조회하는 것으로 보이네요. 그렇다면 이미 존재하는  `findByMemberAndProcessingStatus`를 재사용해도 되지 않을까요?
마찬가지로 '멤버를 기준으로' & '스터디 상태를 기준으로' 조회하기 때문에 이 메서드에서 조회하고자 하는 결과를 조회할 수 있을 것 같네요.

2023-07-20 18:09 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        List<StudyMemberResponse> applicantsOfStudy = findApplicantsOfStudy(study.getId(), study.getCurrentRound()
p2: DTO의 형태가 달라짐에 따라 `findApplicantOfStudy()`를 재사용하지 못하게 될 수도 있을 거 같아요. 이는 뷰의 변화가 서비스 로직에 영향을 미치는 것이라고 생각합니다. 
DTO를 반환하는 서비스 메서드를 재사용하는 대신, Repository에서 `List<Applicant>`를 꺼내오는 것은 어떨까요??

로직은 상당히 깔끔하네요!

2023-07-21 00:32 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        List<StudyMemberResponse> applicantsOfStudy = findApplicantsOfStudy(study.getId(), study.getCurrentRound()
totally 동의합니다!

2023-07-21 00:39 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/domain/study/StudyRepository.java
> +    List<Study> findStartedStudiesByMember(@Param("member") Member member);
아 메서드 이름이 좀 잘못되었네요~ 
이 메서드는 내가 멤버, 방장인 스터디를 조회하는 메서드라서 오해가 생긴 거 같아요. 
이름을 findStudiesOfMember로 이름 변경하였습니다!

2023-07-21 04:26 UTC, yujamint approved these changes
고생하셨어요 에밀. 이만 어프루브하겠습니다~

2023-07-21 06:01 UTC, kevstevie approved these changes

2023-07-21 06:01 UTC, poi1649 approved these changes
긴급 approve

2023-07-21 06:01 UTC, merged