StudyMember에 Role 넣고 리팩터링
woowacourse-teams/2023-yigongil pull request #99
Opened 2023-07-23 10:37 UTC by kevstevie

## 😋 작업한 내용

applicant 엔티티 삭제

role이 생기면서 다른 로직들이 가벼워짐

다른 것도 더 바뀔 것 같은데 일단 이것만

## 🙏 PR Point

테스트는 전부 정상 작동하는데 로직에 허점이 없는지 확인 부탁드립니다

## 👍 관련 이슈

- Resolved : #97

2023-07-24 05:46 UTC, CFalws reviewed
고생하셨습니다~ 하나만 보시면 될 거 같아뇨~

2023-07-24 05:46 UTC, CFalws commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        List<Member> members = studyMemberRepository.findAllByStudyIdAndRole(studyId, Role.STUDY_MEMBER).stream()
p1: 스터디 장이 스상조에서 조회가 안되는 것 같아요~

2023-07-24 07:27 UTC, poi1649 approved these changes
주말에도 고생 많으셨습니다. 사소한 커멘트 남겼으니 확인 부탁드려요 👍 👍

2023-07-24 07:27 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/domain/studymember/StudyMemberRepository.java
> +    void delete(StudyMember studyMember);
p3 : entity를 넘기는 것과 id 를 넘기는 것 둘 중 하나로 통일해줄 수 있으면 좋을 것 같아요 🤔

2023-07-24 07:27 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        return studyMember;
p3: 저희 컨벤션대로면 가장 밑에 위치하는게 맞는 것 같네요

2023-07-24 07:27 UTC, poi1649 commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +        study.addMember(studyMember.getMember());
p3: StudyMember안에 study와 member가 둘 다 있으니, Service단에서 repository에 계속 find 쿼리를 날리는 것 보다, studyMember에 master를 인자로 받는 메서드를 통해 처리하면 더 객체지향적일 것 같아요

2023-07-24 07:28 UTC, yujamint requested changes
코드 작성하느라 고생하셨습니다~ 코멘트 한 번 확인 부탁드려요!

2023-07-24 07:28 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
>      }
p2: 이 메서드는 컨벤션에 따라 `deleteApplicant()` 하단에 위치하는 게 맞는 것 같아요~
```
private 메서드 위치
    - private 메서드를 사용하는 public 메서드 중 가장 아래 쪽 메서드의 아래에 위치
```

2023-07-24 07:28 UTC, yujamint commented on backend/src/main/java/com/yigongil/backend/application/StudyService.java
> +                                .getCode(),
p4: 현재는 Study를 조회하고, Study 수만큼 StudyMember를 조회하여 Role을 구해오는 구조인 것 같아요. 그래서 조회된 Study 엔티티 수만큼 쿼리가 추가로 발생하는 것 같아요.
반대로, StudyMember를 조회하면서 연관된 Study를 fetch join 해오면 어떨까요??

2023-07-24 07:28 UTC, yujamint commented on backend/src/test/java/com/yigongil/backend/acceptance/steps/MyStudyFindSteps.java
> +                .filter(myStudyResponse -> myStudyResponse.role() == 3)
p2: 주드가 작성한 코드는 아닌듯 하지만, filter()의 조건을 매직 넘버가 아니라 `myStudyResponse.role() == Role.MASTER.getCode()`와 같이 수정하면 어떨까요?

2023-07-26 01:33 UTC, CFalws requested changes

2023-07-26 01:33 UTC, CFalws commented on backend/src/test/resources/application.yml
> +      ddl-auto: create
eol 이요!~

2023-07-26 01:33 UTC, CFalws commented on backend/src/main/resources/console-appender.xml
> +</included>
eol이요!

2023-07-26 01:38 UTC, yujamint approved these changes
고생하셨습니다 주드~ 어프루브할게요!

2023-07-26 01:39 UTC, kevstevie commented on backend/src/main/resources/console-appender.xml
> +</included>
수정햇습니다

2023-07-26 01:43 UTC, CFalws commented
굿입니다~

2023-07-26 01:47 UTC, CFalws approved these changes

2023-07-26 01:48 UTC, merged